agents/lakeshore240/LS240_agent.py, agents/lakeshore372/LS372_agent.py, docs/lakeshore240.rst, docs/lakeshore372.rst
This adds automatically starting data acquisition to both the 240 and 372 agents. By default they will initialize and start data acquisition on startup. Users can disable this behavior if they want with a flag or argument configured in their ocs config file.
I've tested with both Lakeshore models at Yale. This likely has some conflicts with the changes in #9, so merging should be handled carefully.
Also adds documentation for both Agents, as well as instructions for first time setup of the 240s, detailing driver installations an pitfalls there.
=> Lakeshore data acquisition autostart

agents/lakeshore240/LS240_agent.py, docs/lakeshore240.rst, socs/Lakeshore/Lakeshore240.py, socs/simulators/ls240_simulator.py
This PR adds a lakeshore240 simulator to socs/simulators, which emulates a lakeshore 240 device and can be controlled with the Lakeshore240.py module. To use it, you can run `python3 ls240_simulator.py` optionally specifying a port for it to use. When connecting the the  Lakeshore Module code, instead of giving the Module the usb port in the init function you can give it an address like `tcp://localhost:1094`, which will connect to a simulator running on port 1094. The simulator is not fully fleshed out yet, but most of the Lakeshore240 commands that we use have been implemented, with the exception of using calibration curves. Right now if you try to get data from it it'll just return white noise around a value that you can specify.
Now that we have this I took all of the fake_data …
=> Ls240 simulator

Dockerfile, agents/bluefors/Dockerfile, agents/keithley2230G-psu/Dockerfile, agents/lakeshore240/Dockerfile, agents/lakeshore372/Dockerfile, agents/pysmurf_archiver/Dockerfile, agents/pysmurf_controller/Dockerfile, agents/smurf-stream-simulator/Dockerfile
Partner PR to [https://github.com/simonsobs/ocs/pull/65](url). Changes docker structure in each image so that socs goes in `/app/socs`, and so that pip install is editable
=> Docker structure

agents/bluefors/bluefors_log_tracker.py, docs/bluefors_agent.rst
This fixes a bug in the Bluefors log Agent that causes the aggregator to crash by accidentally passing a string to the OCS Feed. This issue still needs to be address in the HK Aggregator (see https://github.com/simonsobs/ocs/issues/72), but this solves the problem in the Agent.
We also add some things that were useful in debugging, such as logging, the ability to set the frame length via environment variable, and the ability to set the log level via environment variable.
=> Bluefors Agent data feed bugfix

agents/pysmurf_aggregator/Dockerfile, agents/pysmurf_aggregator/stream_listener.py, agents/timestream_aggregator/Dockerfile, agents/timestream_aggregator/timestream_aggregator.py, docker-compose.yml, docs/index.rst, docs/timestream_aggregator.rst
Use old stream listener as basis for the pysmurf aggregator. This makes minimal
modifications for allowing the listener to run in a container. We also create
the Agent's Dockerfile and add it to the docker-compose file.
Just wanted to get a working baseline to start from. Open to suggestions for naming, etc.
=> Start setup of pysmurf_aggregator from stream listener

agents/lakeshore372/LS372_agent.py
This PR replaces job locking in the LS372 agent with TimeoutLock, so people shouldn't get locked out of functions after they fail. Since the fake_data option doesn't really work with all tasks, I haven't been able to test most of the tasks, so if you want maybe you should test them out with hardware at yale. I have tested the acquisition process, and verified that if it raises an exception you can still call other tasks.
=> Replaced job locking with TimeoutLock

agents/lakeshore372/LS372_agent.py, docs/lakeshore372.rst
The 372 inputs have a user set parameter called "change pause", which has a
minimum of 3 seconds. This is time after switching channels that the 372 waits
before collecting measurements. If the channel is queried in this time it'll
report the same value repeatedly. This means we end up collecting 3 seconds 
(or whatever the pause value is set to) of identical, stale, data points. This patch
addresses that by tracking when channels change, querying the pause setting
and sleeping for that time.
There's also some other minor cleanup that were simple things I noticed while
linting.
=> Add delay in data collection to account for pause

socs/Lakeshore/Lakeshore372.py
Curve upload method not fully reliable (not all 200 data points get fully uploaded at random times). Wrote a method to check uploaded calibration points; if points not uploaded, the method re-uploads calibration points. 
Timeout Error at 50ms; 61ms fixes this issue currently.
=> Check uploaded calibration points

agents/cryomech_cpa/cryomech_cpa_agent.py, docs/agents/pysmurf/index.rst, docs/agents/pysmurf/pysmurf-controller.rst
#38 caused RTD builds to fail due to an unprotected OCS import.
There were also some lingering build warnings from an error in the pysmurf-controller docs, so I addressed those as well.
=> Fix some documentation errors and warnings

agents/lakeshore240/LS240_agent.py
This commit adds a single task to the LS240 Agent for testing the disconnection
of an Agent heartbeat. We use the 240 Agent since it is an easy example that
has an accompanying software simulator.
We also adjust the acq method name to conform to naming conventions and update
its documentation.
Finally, we add txaio logging and a LOGLEVEL environment variable.
=> Add heartbeat control task to LS240 agent

agents/timestream_aggregator/timestream_aggregator.py
Similar to https://github.com/simonsobs/ocs/pull/110, we discussed changing the naming convention of .g3 files to use ctime, rather than the `"%Y-%m-%d-%H-%M-%S"` format. This PR changes the naming scheme in the timestream aggregator.
Edit: Just to be more clear, this means that files will look like "ctime_000.g3", "ctime_001.g3", etc. for sets of observations, broken up into chunks of a configurable amount of time (defaults to 10 minutes.)
=> Update basename convention to use ctime

.travis.yml, Dockerfile, README.rst, tests/README.rst
After writing all those tests for the timestream aggregator I wanted to get this running on travis. This setup matches the setup we have for both the ocs and so3g repositories, where we run the tests within a docker container that has all the required dependencies.
The only potentially conflicting change is the small adjustments I made to the Dockerfile. I did this just to be consistent with how the ocs Dockerfile is organized, allowing the commands for running things to remain consistent across repos. Let me know if the changed WORKDIR is going to disrupt anything.
We also add test coverage reporting via coveralls like we have for ocs and so3g.
=> Add test stage to Travis CI Pipeline

agents/pysmurf_controller/pysmurf_controller.py, agents/pysmurf_monitor/pysmurf_monitor.py, docs/agents/pysmurf/pysmurf-controller.rst
This PR adds a pathway to communicate data from a running pysmurf script to the pysmurf-controller's session data variable.
If you call `S.pub.publish(data, msgtype="session_data")` for some dict `data`, then they pysmurf-monitor will publish `data` to an ocs_feed. The pysmurf-controller will then receive that data, then update the current session's `session_data` variable. The pysmurf-controller needs to be told which pysmurf-monitor to listen to, which can be done using the `--monitor-id` site-arg.
Since there will only ever be one script running at a time, I took Matthew's suggestion and made the controller's tasks all run in the reactor thread. I've tested it and it seems to work fine, but Matthew if you could look at it and verify that it's correct that would be awesome.
=> session_data pathway for pysmurf-controller

agents/lakeshore372/LS372_agent.py
This is accomplished by adding a lock to guard the acq Process from other
runs of the acq Process, then using the usual job lock to guard only
hardware i/o in the acq Process.
Added some helper functions to return the right ContextManager with an
appropriate timeout... these could instead be provided by OCS.
Also removed misleading working in the lock warnings.
=> lakeshore372: allow Tasks to run while acq Process is running

docs/agents/pysmurf/pysmurf-archiver.rst
Not much here to review, but I thought this would be a good place to discuss/finalize how to setup ssh permissions for the pysmurf-archiver so it can copy over files from the smurf-server. The docs describe how I currently set it up at UCSD, and it seems to work and not require much effort. If you have any problems with it let me know, otherwise I'll go ahead and merge it and use this method whenever I set up the archiver.
=> Added docs on how to setup .ssh permissions for pysmurf archiver

agents/pysmurf_archiver/pysmurf_archiver_agent.py, agents/pysmurf_monitor/pysmurf_monitor.py, socs/db/pysmurf_files_manager.py
This PR does two things: 
1. It versions the `pysmurf_files` table in the ocs database so that we can make changes to column structure without getting rid of previous data.
2. Puts a limit (of 5) on the number of failed copy attempts before the pysmurf-archiver gives up on copying a file.
This is to solve an issue where pysmurf will write and publish files that don't have unique names, like `mask.txt`. The table versioning was necessary for me to get rid of the Unique requirement on pysmurf file paths in the database. 
I also realized that we are getting an md5sum error sometimes because pysmurf will write and publish a file, and then that file might be changed after the md5sum is already in the database. I'm not sure what the correct thing to do is here for on the OCS side, but the limit …
=> Added table versioning and failed copy limit

agents/pysmurf_archiver/pysmurf_archiver_agent.py, agents/pysmurf_monitor/pysmurf_monitor.py, docs/agents/pysmurf/pysmurf-archiver.rst, docs/agents/pysmurf/pysmurf-monitor.rst, socs/db/pysmurf_files_manager.py
This fixes the archiver path based on what we decided at the pysmurf meeting, using "pysmurf actions" implemented [here](https://github.com/slaclab/pysmurf/pull/317). With this, the OCS archived path looks something like:
```
base/<5 ctime digits>/<smurfpub_id>/<grouptime_action>/<outputs or plots>/filename
```
Where the grouptime is the pysmurf timestamp at which the top-level function is called, and the action name is set in pysmurf (but right now is usually the smurf function name). For example:
```
/data/pysmurf/15844/smurf_emulator/1584400934_take_stream_data/outputs/1584400934.dat
```
This is backwards compatible with versions of pysmurf without the publisher actions, but we should probably wait on this until the pysmurf branch is merged.
=> Adds pysmurf actions to the pysmurf archiver path

agents/pfeiffer_tpg366/pfeiffer_tpg366_agent.py
The line querying gauge states was causing errors when trying to read channels that were off. I commented out that line so that the agent would stop crashing.
=> Fixing errors on the Pfeiffer agent

agents/pfeiffer_tpg366/pfeiffer_tpg366_agent.py
A typo within the Pfeiffer agent was causing the OCS aggregator to crash. Specifically, the agent was assigning "frame length"  instead of "frame_length". This, and a minor documentation typo was addressed.
=> Addressing typos in the Pfeiffer agent

Dockerfile, agents/bluefors/bluefors_log_tracker.py, agents/cryomech_cpa/cryomech_cpa_agent.py, agents/labjack/labjack_agent.py, agents/lakeshore240/LS240_agent.py, agents/lakeshore372/LS372_agent.py, bin/rename_fields
This PR adds the `rename_fields` script, which attempts to correct all invalid field names that might have been previously recorded in .g3 files across all OCS/SOCS Agents. Since we want to eliminate any invalid field names in current Agents, we also simultaneously make updates to all SOCS Agents with invalid field names.
I've tested this on single days worth of data at Yale, and on single files from UCSD's system. It seems to work, but a review of the functionality of the renamer and additional verification from someone else would be helpful. To help with testing I've added some functionality to the `checkdata` script in ocs (see https://github.com/simonsobs/ocs/pull/147) to identify invalid field names. The sort of ultimate test will be in converting the Yale data set and re-uploading …
=> Rename invalid field names

bin/rename_fields
This adds some tracking functionality to the field renaming script so we don't process all files every time we run the script. It's similar to the tracking in ocs' g32influx script, using sqlite to record the state of processed files. We also add logging, sensible renaming for the M1000 Agent, and progress bars.
=> Track processed files and their output status

.github/pull_request_template.md, .github/workflows/develop.yml, .github/workflows/official-docker-images.yml, .travis.yml, CONTRIBUTING.rst, README.rst, docs/user/installation.rst
This implements nearly identical CI workflows and contributing guidelines to those established for the OCS directory in https://github.com/simonsobs/ocs/pull/146/. Docker builds are moved from Travis CI to GitHub Actions for more fine grained control over image tags, notably triggering official builds on GitHub releases.
One other change, separated in 9273a32, involves changing the recommended installation command set in the docs and README to bring it inline with the recommendation of using pip in the OCS docs, rather than calling `setup.py` directly.
=> GitHub Actions and Contributing Guidelines

agents/smurf_recorder/smurf_recorder.py, agents/smurf_stream_simulator/smurf_stream_simulator.py, docs/agents/smurf_recorder.rst, socs/agent/smurf_recorder.py, tests/agents/test_smurf_recorder.py
This PR modifies the smurf-recorder file path to include the stream-id.
Based on [this](http://simonsobservatory.wdfiles.com/local--files/smurfdaq-user-interface-2020/readout_data_storage.pdf?ukey=4b10d8a49a529d110dc49cb2377d031215082f6d) presentation that Marius gave at the last Smurf-DAQ workshop, detector timestreams should be organized according to 
```
<data_dir>/<date-code>/<stream-id>/files
```
Currently data is just recorded as `<data_dir>/<date-code>/files`, so this must be updated before we can operate with multiple slots. 
This PR adds the `stream_id` variable to the path, which the SmurfRecorder will either pull from a G3Frame if possible, or use a default provided as a command line argument. In the next release of the `smurf-streamer` all frames will be tagged with the …
=> Adds stream_id component to SmurfRecorder file path

bin/rename_fields
Pretty similar to https://github.com/simonsobs/ocs/pull/162, allow for file check to be skipped. And catch raised exception for invalid field names that weren't renamed by the rename file script, flagging them for future investigation, and skipping the file.
The file check skip was useful for debugging the script during processing at UCSD, as we were running into invalid fields, which I wanted to crash hard on initially so we were sure to catch them. However, leaving this running on 10,000 files for hours it became clear that we should just catch this and record the files we need to look at in more detail.
This was used as is during the UCSD hk v2 update.
=> Handle ValueErrors in processing, and allow skipping db check

agents/bluefors/Dockerfile, agents/cryomech_cpa/Dockerfile, agents/labjack/Dockerfile, agents/lakeshore240/Dockerfile, agents/lakeshore372/Dockerfile, agents/meinberg_m1000/Dockerfile, agents/pfeiffer_tpg366/Dockerfile, agents/pysmurf_archiver/Dockerfile, agents/pysmurf_controller/Dockerfile, agents/pysmurf_monitor/Dockerfile, agents/scpi_psu/Dockerfile, agents/smurf_recorder/Dockerfile, agents/smurf_stream_simulator/Dockerfile
Just like https://github.com/simonsobs/ocs/pull/171 we add dumb-init to the Agent entry points.
Solves the issue raised in https://github.com/simonsobs/ocs/issues/168.
Individual containers are untested, however adding dumb-init isn't expected to cause any issues.
=> Add dumb-init to Agent container entrypoints

agents/smurf_recorder/smurf_recorder.py, agents/smurf_stream_simulator/smurf_stream_simulator.py, socs/agent/smurf_recorder.py
This PR adds functionality to the smurf_recorder agent to monitor specified readout channels, downsample incoming data for those channels, and sends them to grafana.
This adds two new tasks to the smurf recorder agent. `set_monitored_channels` will set update the list of channels to stream, and `set_target_rate` sets the sample rate that the detector data will be downsampled to.
It also adds a function `read_stream_data` to the `FrameRecorder` class that loops through incoming frames and records downsampled data for the monitored channels so it can be published by the agent.
This PR also changes the G3TimestreamMap keys in the smurf_stream_simulator to be the same as the data currently passed by the real smurf-streamer (e.g. 'r0012' instead of '12').
This will allow detector data to be …
=> Addes stream monitor to the smurf_recorder agent

agents/cryomech_cpa/Dockerfile, agents/labjack/Dockerfile, agents/lakeshore240/Dockerfile, agents/lakeshore372/Dockerfile, agents/meinberg_m1000/Dockerfile, agents/pfeiffer_tpg366/Dockerfile, agents/pysmurf_archiver/Dockerfile, agents/pysmurf_controller/Dockerfile, agents/pysmurf_monitor/Dockerfile, agents/scpi_psu/Dockerfile, agents/smurf_recorder/Dockerfile, agents/smurf_stream_simulator/Dockerfile, agents/synacc/Dockerfile, docs/agents/lakeshore240.rst, docs/agents/pysmurf/pysmurf-archiver.rst, docs/agents/pysmurf/pysmurf-controller.rst, docs/agents/pysmurf/pysmurf-monitor.rst
Replace all Dockerfile default CMDs that specify 'sisock-crossbar' with just 'crossbar'. Also replace instances in the documentation.
Upstream, OCS has made this change, redrawing the boundary between OCS and sisock (https://github.com/simonsobs/ocs/issues/135). For compatibility we should do the same here.
Not yet tested, but changes follow from OCS where this has been tested. Plus it's just a configuration change, however one that needs to be announced.
=> Replace 'sisock-crossbar' with 'crossbar'

socs/agent/smurf_recorder.py
Clamps the downsample factor in smurf_recorder's stream monitoring function, solving #122.
Slicing with step size larger than the length of the would cause spt3g to log a fatal error.
Tested running this locally with the smurf-recorder with `target_rate=0.1` and short file sizes.
=> Clamp ds_factor in smurf recorder

Dockerfile
This introduces so3g v0.1.0-24-g5645096 and all that comes with it, including
Int64 support in G3VectorInts.
Will merge once tests pass.
=> Bump ocs version to v0.7.1-9-g500447e-dev

agents/pysmurf_controller/Dockerfile
bump pysmurf-controller to socs version v0.1.0 to fix schema error in pysmurf.
Will merge if tests pass because it's needed at UCSD.
=> bump sodetlib version

.github/workflows/develop.yml, .github/workflows/official-docker-images.yml, .github/workflows/pytest.yml, agents/labjack/Dockerfile, agents/labjack/labjack_agent.py, agents/labjack/requirements.txt, docs/agents/labjack.rst
The previous labjack commit did not actually implement the labjack ljm module necessary for high sample rates. This does that. It also:
- Publishes data in blocks at no faster than 1Hz, eliminating the problem of dropped data at >100Hz sample rates.
- Implements a 2nd feed downsampled to no faster than 1Hz for use in influx (and excludes the main feed from influx)
- Changes the channel names to AIN0, AIN1, etc rather than Channel_1, Channel_2, etc
- Fixes issues with the 'T7-all' and 'T4-all' commands
- Updates documentation
Solves:
- not being able to sample >100Hz
- 'T7-all' and 'T4-all' not working
- Channel names that didn't align with their names on the labjack
- Tested the main and downsampled feeds work from 0.1Hz to 5000Hz. 
- Confirmed the main feed is not published to influx
- …
=> Implement labjack ljm functionality to allow high sample rates

agents/pysmurf_controller/requirements.txt
Adds dumb-init to the pysmurf-controller requirements file.
Since the pysmurf-controller is built on the sodetlib image and not socs, it did not have dumb-init installed by default which was preventing it from starting correctly. This fixes it by adding it to the Docker requirements file.
Resolves https://github.com/simonsobs/smurf-issues/issues/16.
Tested by running the agent locally and checking that it actually started instead of throwing the error mentioned in the smurf-issue.
=> Added dumb-init to pysmurf-controller reqs

agents/pysmurf_archiver/pysmurf_archiver_agent.py, agents/smurf_recorder/smurf_recorder.py
Adds `set_status` calls to SmurfRecorder and SmurfArchiver operations.
Adds `set_status` calls to SmurfRecorder and SmurfArchiver operations.
Status was showing up as `starting` and never changed to `running` in the grafana operations monitor.
=> Adds set_status calls to some operations

agents/tektronix3021c/tektronix_agent.py
Move the docstring from the `__init__()` method to the class, and switches "params:" to "Args:" so that things format correctly in the Sphinx docs.
=> Fix docstring on TektronixAWGAgent class

socs/agent/smurf_recorder.py
Removes the check-port test from the smurf-recorder
Removes the check-port test from the smurf-recorder
Recently noticed that the check port option isn't consistently representing whether a G3Streamer is running on that port. I just noticed that it was failing this check, and not connecting to the G3Reader. I believe the difference from when I tested before is that we switched to connecting to the port on the smurf-server directly instead of using a tunnel, which may have changed the behavior of the check_port function.  Best to just take this check out and deal with the log_fatal messages before it causes more problems.
Tested on k2so
=> Remove check_port test

agents/labjack/labjack_agent.py
If the labjack is disconnected, the data stream will still be active. The previous version of this agent would then throw an error when the agent is restarted, since you can't start a stream if one is already running. The fix here is to check for this error, and if it occurs, stop the stream first. (A cleaner way would be to check if the stream is running, but I couldn't figure out how to do that).
See the description. I noticed this error at UCSD when the ethernet from the labjack was disconnected while the agent was running.
I reproduced the error without the agent changes implemented, then confirmed that the changes stopped the stream and sucessfully started it again.
=> Catch labjack stream error

docs/agents/bluefors_agent.rst, docs/agents/lakeshore240.rst, docs/agents/lakeshore372.rst, docs/agents/pysmurf/pysmurf-archiver.rst, docs/agents/pysmurf/pysmurf-controller.rst, docs/agents/pysmurf/pysmurf-monitor.rst, docs/simulators/ls240_simulator.rst
This expanded a bit from my initial goal of updating the 372 Agent docs. There were several aspects of the 372 docs that were similar in other Agents that I thought needed some updating. These updates are:
* Remove mention of sisock -- i.e. updates from "sisock-crossbar" to "crossbar" where needed, mention of sisock-data-node-servers
* Removal of `depends_on: crossbar` from example docker-compose configurations. We made the recommendation to separate crossbar from main compose files, so this'll not work anymore. It never really did the thing we wanted, which is wait for crossbar to come up before starting the agents that depend on it. But it's also not really a problem any more, ever since https://github.com/simonsobs/ocs/pull/180.
* Update image URLs from the old docker registry we …
=> Remove mention of sisock data feed servers from 372 docs

agents/chwp/Dockerfile, agents/chwp/hwpbbb_agent.py, docs/agents/chwp_encoder.rst, docs/index.rst
Here are some small suggestions to latest chwp agent PR (https://github.com/simonsobs/socs/pull/80). To maybe save a back and fourth on changes I just made updates as I re-reviewed the Agent. A quick summary:
* Found some small typos in the Sphinx docs, fixed those and added the new page to the index so it'll appear in the sidebar.
* Protected the ocs import for the automated documentation build (else that system fails to build the docs and publish to the web)
* Caught two tabs in the agent file, replaced them with spaces
* Added "dumb-init" an init system we started using recently within the Docker containers. Also removed "sisock-" from the default commands, as that's been removed from the OCS system.
* Added the [recommended logging …
=> CHWP Agent Feedback

agents/chwp/Dockerfile, agents/chwp/hwpbbb_agent.py, docker-compose.yml, docs/agents/chwp_encoder.rst, docs/index.rst
This is for a new agent for the CHWP encoder DAQ to receive and publish the data sent from Beaglebone Black reading the encoder and timing signals. This agent has three different data feeds for IRIG-B and the encoder counter and quadrature because the data rates are different.
Note that this is a bit newer than the one running currently with the real CHWP at UCSD, but this version of the agents is also tested with the other beaglebone test setup using a function generator.
=> New CHWP encoder readout agent

agents/smurf_stream_simulator/smurf_stream_simulator.py, docs/simulators/smurf_stream_simulator.rst
Add a `--stream-id` argument to the SMuRF Stream Simulator Agent so we can set it in the site config file.
Needed this for scale testing with many different stream simulators running at once so I could output data to different directories, as those are set by the stream-id.
This is being used currently in some scale testing currently with 14 simulators running on the same machine.
=> Add stream-id argument to smurf stream simulator agent

agents/ocs_plugin_so.py, agents/xy_stage/xy_latrt_agent.py, agents/xy_stage/xy_ocs_agent.py, docs/agents/latrt_xy_stage.rst
Adds an agent for interacting with the XY Stage controller we're using with the LATRt. 
We want position readout in `.g3` files. Which means we also need to control the device through OCS.  
It's been tested for the use-cases we need for beam mapping. The lower level controller has the safety features.
=> Add XY Stage Agent for LATRt Stages

docs/agents/scpi_psu.rst
@zhuber21 found a missing config option in the SCPI PSU Agent docs. Copying them as is will likely result in connection issues. The Agent should be on the host network to properly see the PSU's IP.
=> Add network_mode to docker-compose example in SCPI PSU Agent docs

agents/pysmurf_controller/Dockerfile
Updates sodetlib version to most recent, and removes ocs install since that is now done in the sodetlib docker.
Tested with ocs-pysmurf-controller and emulator on smurf-srv-so3.
=> bump sodetlib and remove ocs install

agents/lakeshore372/LS372_agent.py, socs/Lakeshore/Lakeshore372.py
This introduces some error handling for connection errors to the 372 on Agent startup. When establishing the connection in the init task we watch for an OSError, make sure it relates to a ConnectionError and raise that for handling in the Agent.
Within the Agent we catch the ConnectionError and shutdown the reactor, exiting the Agent. 
fixes #164 
This has been tested against a powered off LS372 at Yale.
=> Handle LS372 ConnectionError if device powered off at Agent startup

agents/pysmurf_monitor/pysmurf_monitor.py
This PR adds a pipeline for publishing Rogue Metadata variables to an OCS feed. The smurf-server publishes specified metadata variables whenever they are queried, or regularly at some polling interval specified by the smurf-streamer.
This PR adds support for publishing Rogue Metadata updates to OCS feeds. The meta-data values which we want to monitor through this path can be set with the [meta registers file](https://github.com/simonsobs/smurf-streamer/blob/master/meta_registers.yaml), by making the variable group `2` if you want to just publish the variable through pysmurf, or `3` if you want to publisher the variable through pysmurf and send through the g3 stream. Setting the polling interval in that file will determine how often updates are published.
With [this …
=> Adds an OCS pathway for smurf metadata

agents/bluefors/Dockerfile, agents/bluefors/bluefors_log_tracker.py, docs/agents/bluefors_agent.rst
Update the Bluefors Agent to handle a change in inode of logfiles.
The Bluefors Agent was originally built to run on Docker for Windows. This was because at the time I ran into issues running on Linux and syncing the logs continuously when it came to keeping track of the active log files. This was dependent on the configuration a bit. The Bluefors software writes to simple .csv files on Windows, and I was using a tool called Syncthing to copy them as they were updated to a Linux box. The Linux box was running the Agent, which would keep files open and continously try to `readline()`. On copy the inode changed, and Python lost track of the file. It worked if you followed the files directly on Windows though, so we ended up with the Docker on Windows solution people currently run.
Docker on …
=> Bluefors inode handling

docs/agents/smurf_crate_monitor.rst
=> Update smurf crate monitor agent docs to use docker hub image

.coveragerc, .github/workflows/develop.yml, .github/workflows/official-docker-images.yml, .github/workflows/pytest.yml, README.rst, agents/lakeshore372/LS372_agent.py, tests/agents/test_bluefors_agent.py, tests/agents/test_ls372_agent.py
Testing that Agents still function after changes are made is difficult without hardware access, which may be limited by local availability or if hardware is currently in use. This is an attempt to demonstrate unit testing and test coverage on an Agent, mocking the communication layer and returning example responses from a device. This should allow for rapid testing of the Agent Task/Process functionality without access to hardware.
This isn't, however, a full test of Agent functionality, nor is it any sort of integration testing of an Agent on an active OCS network. This would not catch errors related to Agent startup, or errors on the Client side -- particularly anything related to improper parameters being passed to a task/process, as ParamErrors are raised on the client side start …
=> Create example Agent unit tests

.github/workflows/develop.yml, .github/workflows/official-docker-images.yml, .github/workflows/pytest.yml, docker-compose.yml, requirements.txt
This PR introduces the pytest-order plugin in order to make sure that the spt3g import test runs first when running spt3g dependent tests. This ensures that those tests are not skipped, which happens if the spt3g import test isn't run first. This seems to happen randomly, which caused an unexpected coverage drop on https://github.com/simonsobs/socs/pull/220.
While testing locally I noticed that the docker-compose doesn't mark the Agent images as dependent on the socs image. I've added that here as well.
Fixing random coverage drop seen in https://github.com/simonsobs/socs/pull/220 caused by inconsistent test ordering (ideally tests don't have an order dependence, but since we're checking for an imported package and using the result with pytest-dependency, we do have this requirement.) …
=> Enforce ordering of tests for spt3g dependency check

agents/lakeshore425/LS425_agent.py, docs/agents/lakeshore425.rst, socs/Lakeshore/Lakeshore425.py
Just a few last suggestions on the Lakeshore425 Agent.
- Apply the param decorator to all tasks/processes.
- Add the Agent docs to the documentation page.
- Add the `any_command` output to `session.data` for inspection on the Client end.
@ykyohei, if these changes look alright to you we can merge into your branch, then merge #221. These are mostly documentation changes, but also testing the tasks/processes with new param decorators would be good, but I don't expect any major issues there.
Happy to answer any questions about any of the changes.
=> Lakeshore425 Agent Suggestions

tests/config.json, tests/default.yaml, tests/docker-compose.yml, tests/integration/test_ls372_agent_integration.py
Change crossbar port from 8001 to 18001 for running the tests, moving it out of the way of any normally running crossbar server on the system performing the testing.
Fixes #214
Run with local testing. Should pass checks here as well.
=> Change default port for crossbar used in testing

.github/workflows/develop.yml, .github/workflows/official-docker-images.yml, .github/workflows/pytest.yml, Dockerfile, socs/testing/device_emulator.py, tests/default.yaml, tests/integration/test_ls425_agent_integration.py, tests/integration/util.py
This creates integration tests for the Lakeshore425 Agent, using the new `DeviceEmulator`. This runs the LS425 Agent directly, mocking communication with a device via the `DeviceEmulator`.
This makes use of some newly moved upstream testing tools in ocs, so I've also bumped the ocs base image version in the `Dockerfile` here.
@ykyohei You might be interested in this, so I've added you as a reviewer. The one "response" from the Lakeshore425 that I'm a little unsure I'm representing realistically is the response to `OPST?`. Is `001` a realistic response from the device?
I wrote these (and the `DeviceEmulator`) while working on issues that came up during #225.
Tested locally, and now in the CI pipeline.
=> Create Lakeshore425 Agent integration tests

agents/lakeshore372/LS372_agent.py, socs/Lakeshore/Lakeshore372.py, tests/integration/test_ls372_agent_integration.py
Get rid of sleep times in LS372 driver code to increase sampling rate. However, LS372 devices can only readout at a maximum of 10Hz; anything higher and previous points are repeated, so no useful information provided past 10Hz. Implementing Pacemaker in the LS372 agent keeps the device at the maximum sampling rate of 10Hz. 
Initially, LS372's were reading out at ~2Hz (as observed at Princeton). A higher sampling rate was requested. 
Tested on Yale's setup to ensure things don't fail when removing sleep times in driver code. Tested Pacemaker on Yale's setup to ensure 10Hz sampling rate can be deployed.
=> update LS372 sampling rate

socs/testing/device_emulator.py
This removes some f-string syntactic sugar that I used in this module.
I forget where I picked it up, but pretty sure this is a 3.10 feature. I shouldn't have used it. It's causing the docs build to fail silently on the autodoc of this module.
I noticed these were broken today.
Tested a hidden build on rtd.
=> Fix testing docs API autodoc

agents/pysmurf_monitor/pysmurf_monitor.py
Pysmurf monitor used to use the old `Provider._enforce_field_name_rules`, but that was recently moved to the  OCS Feed class. This updates the pysmurf-monitor function call.
Update the pysmurf-monitor function call of enforce_field_name_rules.
See above.
Technically not going to be able to test until Monday, but this seems pretty straightforward.... or I can wait until I actually test it.
- [] I have updated the documentation accordingly.
=> changes monitor to use Feed.enforce_field_name_rules

tests/integration/test_ls372_agent_integration.py
This test occasionally would fail due to it taking longer than typical to run through the acq process. Add a wait to ensure it's done before checking the OpCode. This is fine since we're in the test mode "run_once".
On the recent merge to develop the first run failed with:
```
============================= test session starts ==============================
platform linux -- Python 3.8.12, pytest-7.0.0, pluggy-1.0.0
rootdir: /home/runner/work/socs/socs/tests, configfile: pytest.ini
plugins: docker-compose-3.2.1, dependency-0.5.1, cov-3.0.0, twisted-1.13.4, order-1.0.1
collected 91 items / 64 deselected / 27 selected
integration/test_ls372_agent_integration.py ....F...............         [ 74%]
integration/test_ls425_agent_integration.py .......                      [100%] …
```
=> Fix flaky ls372 acq test

socs/Lakeshore/Lakeshore240.py, socs/testing/device_emulator.py, tests/default.yaml, tests/integration/test_ls240_agent_integration.py
Create integration tests for all of the LS240 Agent's Tasks/Processes. In doing so I removed a trailing semi-colon that has been included in commands sent to the 240. This can be used as a delimiter to send multiple commands at once, but we aren't doing that, so for consistency with other Lakeshore device code in socs I've removed it.
I also added a feature to the Device Emulator which allows you to set a default response to get back if the command is unrecognized, this is convenient here when sending lots of commands (i.e. not queries) where we would expect to just get back empty strings.
Expanding test coverage. Also, this is the only other Agent that communicates over serial, and after getting the Device Emulator written I wanted to write tests for it. …
=> Create integration tests for the LS240 Agent

agents/lakeshore372/LS372_agent.py, docs/agents/lakeshore372.rst, tests/default.yaml
This matches the 240 Agent, allows slightly more control, and now defaults to acquiring data. The problem with the old flag was that if it was missing from a config file the Agent wouldn't start acquiring. Acquire by default is a requested feature and should be the default.
This will require some updates to user configs if they've updated socs since --auto-acquire was implemented, we should warn about that in the release notes. (I'm planning on making a long over-due release of socs after this is merged.)
When users would update they'd typically be missing this flag, would not see data in Grafana, and would report the Agent as broken and downgrade. We should acquire by default.
Tested locally with the integration tests.
=> Replace --auto-acquire with --mode in 372 Agent

agents/pysmurf_monitor/pysmurf_monitor.py
This should fix a small bug in the pysmurf-monitor where numpy files that were registered without the `.npy` extension were not being added to the database correctly. This is because numpy will automatically add that extension if it doesn't exist, meaning the registered file path is not the same as the real file path.
The monitor used to catch this and fix it, but looks like I missed that when I was restructuring the agent. This adds it back.
Catches for npy files without the .npy extension.
We need to archive tunefiles
Not tested yet, but can test later this week on k2so (or maybe @kmharrington can test before then?)
=> Fix npy extension issue

agents/pysmurf_controller/Dockerfile
This effectively replaces installing dependencies via requirements.txt with those specified in setup.py. This avoids installing so3g, which we don't need here, and which doesn't support python3.6, which is what the sodetlib image is on.
#257 added so3g to the requirements file, which [broke](https://github.com/simonsobs/socs/runs/5305731607?check_suite_focus=true) the pysmurf-controller image build.
```
Collecting so3g (from -r socs/requirements/testing.txt (line 6))
Could not find a version that satisfies the requirement so3g (from -r socs/requirements/testing.txt (line 6)) (from versions: )
No matching distribution found for so3g (from -r socs/requirements/testing.txt (line 6))
The command '/bin/sh -c git clone https://github.com/simonsobs/socs.git     && pip3 install -r …
```
=> pip install socs directly from socs repo in pysmurf-controller image

.github/workflows/deploy.yml, .github/workflows/develop.yml, .github/workflows/pytest.yml, tests/default.yaml, tests/docker-compose.yml, tests/integration/test_ls372_agent_integration.py
This replaces the use of the Lakeshore 372 simulator docker container with the socs device emulator fixture for the Lakeshore 372 Agent's integration tests. This will likely resolve the flaky tests we see in those integration tests.
Small coverage reduction due to starting on 'idle', rather than on 'init'.
Fixes #256.
I've run the modified tests locally.
=> Replace ls372 simulator with device emulator in integration tests

.github/workflows/skipped-pytest.yml
Title says it all.
Realized in working on https://github.com/simonsobs/socs/pull/287 that the dummy pytest workflow didn't run, even though I thought it should. This lead me to realizing that it shouldn't be the exact inverse of pytest.yaml, it just needs to run on PRs only, which might make it run in the case I'm considering.
It hasn't been. Yet.
=> Only run dummy workflow on PRs not on push

agents/scpi_psu/scpi_psu_agent.py
Added ability to monitor subset of channels
I added a line to parse the parameters of the start_monitor function for a list of specific channels to monitor, instead of the function monitoring all channels only. By default, if no channels are specified, the function works in the same way it did before the change.
In some circumstances, trying to monitor all channels will crash the agent because the psu won't respond to messages requesting the voltage/current on that channel. This causes the socket to timeout on the socket.read() call in the PrologixInterface class. This occurred when one channel on the psu was set to "in series" mode. By allowing the user to specify which channels to monitor, we can avoid this problem by just not monitoring the problem channel. 
This was tested using a …
=> Scpi psu monitor update

.flake8, .github/workflows/develop.yml, .github/workflows/pytest.yml, .github/workflows/skipped-pytest.yml, .github/workflows/skipped-test-build.yml, .github/workflows/test-build.yml, .pre-commit-config.yaml, CONTRIBUTING.rst
This PR configures [pre-commit](https://pre-commit.com/) to run a few different hooks. The base hooks, provided by pre-commit (with descriptions from https://pre-commit.com/hooks.html):
- check-ast - simply checks whether the files parse as valid python.
- check-yaml - checks yaml files for parseable syntax.
- end-of-file-fixer - ensures that a file is either empty, or ends with one newline.
- trailing-whitespace - trims trailing whitespace.
Additional hooks (from external plugins):
- autopep8 - runs [autopep8](https://github.com/hhatto/autopep8), which automatically formats Python code to conform to [PEP8](https://peps.python.org/pep-0008/).
- flake8 - runs [flake8](https://github.com/PyCQA/flake8), catching any linting that autopep8 doesn't auto-format.
As is in this PR, this is not …
=> Configure pre-commit

agents/fts_aerotech_stage/fts_aerotech_agent.py, docs/agents/fts_agent.rst
Updates fts_aerotech_agent to work with an inputted .YAML config file stored in $OCS_CONFIG_DIR. This config includes some FTS-specific parameters which vary depending on the FTS used or the type of data being taken.
Originally the FTS params were hard-coded in before the class definition. Making the params configurable from a YAML file creates flexibility if they need to change and is necessary since we now have two different FTSes in use.
Awhile back I tested the changes in the LATRt test environment and I was able to work both Uchicago's original FTS and the one we were sending to UCSD with this branch. Admittedly I haven't tested this in awhile though and it could be that things are broken with updated socs. And I haven't used any official test suites.
=> Update FTS aerotech agent to work with multiple different FTSes

agents/magpie/magpie_agent.py, docs/agents/magpie.rst
Makes a few small changes to the Magpie agent for P10R1, including better demodulation, a white-noise monitor, and some small bugfixes.
Changes format of the FocalPlaneConfig object and make it easier to add in more data values and equations. Also adds better data demodulation, and adds a white noise calculator. White noise quantiles will be published to an OCS feed each frame.
White noise monitor is needed for P10R1. FocalplaneConfig restructuring was required so we can more easily add lyrebird datavalues and equations to visualize as we start to pull data from more sources.
White noise monitor!
Tested locally reading G3Frames from a file from an old k2so cooldown.
=> Magpie updates and white noise monitor

.github/workflows/develop.yml, .github/workflows/pytest.yml, .github/workflows/skipped-pytest.yml, .github/workflows/skipped-test-build.yml, .github/workflows/test-build.yml
I realized with the submission of #311 that my work in #286 (specifically ae00541) prevents the test workflow from running when an external collaborator submits a PR. We want this behavior, I think even at the cost of the workflow running twice. If anything probably we should stop running it on every push, though I do find that useful for when preparing to PR to avoid spamming everyone. (Edit: I've decided to actually do this and have removed the run trigger on push.)
Also I realized in another recent PR that the wildcards I setup for matching to .rst and .md files weren't match-y enough. Fixed that as well.
Trying to get #311 merged.
Will be tested on new PRs.
=> Run pytest workflow PR only and fix wildcard pattern matching

agents/cryomech_cpa/cryomech_cpa_agent.py, tests/integration/test_cryomech_cpa_agent_integration.py
Fix bug in the calling of `acq.start()` within the `init` Task where no `params` argument was being passed and the `acq` Process was failing at the param decorator check.
This has been seen before and reported here: https://github.com/simonsobs/ocs/issues/251
This was discovered while trying to test the new on/off functionality. While testing we also found that the echoed response from powering on/off would end up coming back once `acq()` was restarted. Changes in 7519ac12b700611912aa719876c9f8573b698ca8 simply discard the echoed response.
Discovered while testing updated version of the Agent at Penn.
New test written for the auto startup of acq, which would fail before these changes. And all changes tested on an actual compressor at Penn.
=> Fix Cryomech CPA Agent acq process auto start

agents/pysmurf_controller/Dockerfile
This is a temporary fix for the pysmurf-controller builds, which are still based on Ubuntu 18.04 images and only have Python 3.6. Should only remain in place until the sodetlib images can be updated.
#316 broke the docker image builds with the python_requires>=3.7 update (which is propagating from so3g+ocs.) We need the builds to keep working for now though.
Built the image successfully locally.
=> Install socs from temp branch w/o python_requires>=3.7

agents/smurf_file_emulator/smurf_file_emulator.py, docs/agents/smurf_file_emulator.rst, tests/agents/test_smurf_file_emulator.py
Modifications to the SmurfFileEmulator agent, adding realistic tune-files and additional tasks matching those in the pysmurf-controller
Adds realistic tune files and channel assignment files to tune uxm_setup / relock tasks, and adds relevant data to the status dump frame. This is required for emulated data to be indexable by G3tSmurf. 
Adds the DataStreamer class, which makes it easier to create fake g3 streams.
Renames `tune_dets` to `uxm_setup` (and `uxm_relock`) and adds a few tasks that correspond with pysmurf-controller tasks (`take_noise`, `take_bgmap`, `uxm_relock`).
Tune support makes the data outputs indexable with G3tSmurf.
Tested creating files locally, and tested indexing / loading them using G3tSmurf.
=> Smurf emulator tune support

agents/hwp_rotation/src/pid_controller.py
This improves a flaky test for the HWP Rotation again PID controller by attempting the PID controller connection again after a second if it fails to connect the first (or second) time.
The pid controller tests can be kind of flaky when all tests are run. This seems to be because the device emulator isn't quite ready yet. I've seen it vary a lot when run on Github Actions.
A recent failure: https://github.com/simonsobs/socs/runs/7415872076?check_suite_focus=true 
I've reproduced the flakiness locally by running:
```
$ python3 -m pytest -s --cov --cov-report html agents/test_suprsync_agent.py agents/hwp_rotation/test_pid_controller.py
```
Running separately doesn't quite do it, but running another test beforehand generates the error more often than not.
After adding the patch I haven't seen …
=> Attempt failed connection again in pid_controller

agents/chwp/Dockerfile, agents/chwp/hwpbbb_agent.py, docs/agents/chwp_encoder.rst
Put the `approx_hwp_freq` in the `acq` process' `session.data` object for SupervisorAgent to inspect `approx_hwp_freq` in shutdown operation.
The `acq` process of hwpbbb agent doesn't always publish encoder data or update `session.data` in all loops, `session.data` will keep last updated non null `approx_hwp_freq`.
Removed unnecessary EXPOSE from Dockerfile.
For Supervisor Agent to inspect 'approx_hwp_freq' in shutdown operation.
Tested at CHWP setup at UTokyo
=> Put the approx_hwp_freq in session.data object for SupervisorAgent

agents/suprsync/suprsync.py, bin/suprsync, socs/db/suprsync.py
Fixes a bug in the suprsync agent where failed_copy_attempts wasn't being updated.
Changes 'copy_files' function so that if md5sums don't match at the end of the function, failed_copy_attempts will be incremented. Before, `failed_copy_attempts` was built into the database, but I think after the latest refactoring it just never gets updated. 
This also fixes an issue with getting files from the db where files weren't being filtered by failed_copy_attempts
Also changes `max-copy-attempts` default from None to 5 so it doesn't attempt to copy files forever by default.
Also adds better handling of files where it can't find the local path on the host (different issue, but found during the same debugging session)
to fix the system at Penn, where local file overwrites made it was impossible to …
=> Suprsync update copy attempts

agents/ocs_plugin_so.py, agents/suprsync/suprsync.py, socs/db/suprsync.py
Modifications to suprsync for use in LAT testing, where we had a low bandwidth connection (at least some of the time).
This is a feature request in the form of a PR ... @jlashner let me know if you'd rather this be done differently.
New options:
- `--compression`: enables the -z switch to rsync
- `--bwlimit`: pass through to --bwlimit (bandwidth limit) switch of rsync
New method in SupRsyncFilesManager to just return a list of registered files... this helps auto-sync scripts to not re-add files that are already entered... maybe there's already some other way to do this?  I didn't notice the bin/suprsync script when I worked out a solution for our tests.
This version is running at LAT testing now.
=> New control options for suprsync

agents/acu/acu_agent.py, agents/acu/scan_helpers.py
Include new string parameter az_start to indicate the beginning point
of a generator scan. Defaults to starting scans from the midpoint between
the two az endpoint inputs.
=> New parameter for scan start position in generator scans

agents/cryomech_cpa/cryomech_cpa_agent.py, tests/integration/test_cryomech_cpa_agent_integration.py
Added release and acquire function to `acq` process in cryomech cpa agent to release the lock so that short operations like `power_ptc` can run without stopping and restarting `acq`
Keeps the user from having to stop and restart `acq` process
Wrote release and reacquire integration test for cpa agent to make sure the lock releases to run a task during acq process
=> Add release and acquire function to cryomech cpa agent

agents/ibootbar/ibootbar.py, docs/agents/ibootbar.rst, tests/integration/test_ibootbar_agent_integration.py
Removed auto-start param from iBootbar agent, instead set mode to either 'acq' or 'test' (used in integration test)
Integration test needed acq process to not auto start
Pytest passes
=> iBootbar removed auto-start

docs/agents/fts_agent.rst, docs/agents/hwp_encoder.rst, docs/agents/lakeshore370.rst, docs/agents/latrt_xy_stage.rst, docs/agents/pfeiffer.rst, docs/agents/scpi_psu.rst, docs/agents/smurf_crate_monitor.rst, docs/agents/synacc.rst, docs/agents/tektronix3021c.rst, docs/agents/vantage_pro2.rst, docs/agents/wiregrid_encoder.rst, docs/conf.py, socs/agents/fts_aerotech/agent.py, socs/agents/hwp_encoder/agent.py, socs/agents/lakeshore370/agent.py, socs/agents/lakeshore372/agent.py, socs/agents/pfeiffer_tpg366/agent.py, socs/agents/scpi_psu/agent.py, socs/agents/smurf_crate_monitor/agent.py, socs/agents/synacc/agent.py, socs/agents/tektronix3021c/agent.py, socs/agents/vantagepro2/agent.py, socs/agents/xy_stage/agent.py
This PR catches up on many of the Agent docs left after last year's documentation hack day (#208). It standardizes the documentation formatting in the following agents:
- SMuRF Crate Monitor
- HWP BBB Encoder
- Weather Monitor
- Synaccess
- SCPI PSU
- Pfeiffer TPG 366
- Tektronix AWG
- FTS Linear Stage
- LATRt XY Stage
- Lakeshore370
It also adds use of the `@ocs_agent.param` decorator, and where appropriate, modifies the tasks/processes to remove checks on valid params passing, as that check is now handled by the decorator.
This has been on my to do list for a year, and I wanted to get it done before releasing v0.4.0.
Not tested yet, except for where Agents have unit/integration tests.
=> More docs standarization

docs/agents/bluefors_agent.rst, docs/agents/pysmurf-controller.rst
Fixes the example agent docker configuration blocks to have consistent usage of `=` instead of `:`.
Note this doesn't require users to change their existing configs.
A mix of `=` and `:` will cause issues. Cornell saw this when updating recently (thanks @zhuber21 for the report!)
Cornell switched to consistent usage and it resolved their problem.
=> Make docker-compose examples consistent

.github/workflows/pytest.yml, tests/agents/test_pysmurf_controller_agent.py
This changes some of the tests to mock out the sodetlib functions a higher level. This is needed so that they don't depend on the sodetlib internals as much. Of course, if sodetlib function return values change significantly the mocked up values here will need updating.
I had some questions that came up while working on this that'd be good to answer/incorporate here.
* What shape is `bsa.bgmap` typically? Here it's (12, 2), probably that's right, I just wanted to double check for myself.
* What's the `session.data` look like for `take_iv` on a live system?
[Tests were failing](https://github.com/simonsobs/socs/actions/runs/3698000088/jobs/6263663111) on the update to sodetlib v0.5.0 being done following P10R1, in prep for P10R2. See https://github.com/simonsobs/socs/pull/376.
Tested …
=> Rework pysmurf controller tests for sodetlib v0.5.0

docker/pysmurf_controller/Dockerfile, tests/agents/test_pysmurf_controller_agent.py
This PR fixes a bug where socs wasn't properly installed in the pysmurf-controller dockers due to the inclusion of the `-e` flag.
Removes the -e flag
Resolves #394
=> Removes -e from socs install

docs/agents/magpie.rst, socs/agents/magpie/agent.py
Adds an argument to magpie that lets you set a wafer's rotation about its center.
Necessary for bringing up a focal-plane in lyrebird
Tested locally with fake data.
=> Adds rotation arg to magpie

.github/pull_request_template.md, .github/workflows/develop.yml, CONTRIBUTING.rst, README.rst, docker/pysmurf_controller/Dockerfile, docs/user/sequencer.rst, tests/README.rst
This is just following the lead of ocs (see https://github.com/simonsobs/ocs/pull/309.)
`main` will be made the default branch, effectively replacing `develop`. This probably won't happen until Monday (in case something breaks.) The old branches will stick around for a bit while we migrate.
Releases are cumbersome to make, and stable installations can now be done via PyPI (or on version tags here from the repo.)
I've checked some things on this branch, but external services sort of need us to take the plunge before they will work as expected. This whole transition went pretty smoothly in ocs though, so I don't expect any issues.
=> Replace master and develop branches with "main" branch

tests/common/test_moxa_serial.py, tests/common/test_pmx.py
This PR changes the ports used for the device emulator in tests from `tests/common/`.
In a recent test run in #343 these weren't cleaning up in time for the next test, causing an error. This could be solved at a lower level, but moving ports is a quick and easy solution. No need to always bind to the same one across all tests.
Run here: https://github.com/simonsobs/socs/actions/runs/4185908565/jobs/7253644486
=> Move port numbers for binding in common tests

socs/agents/smurf_file_emulator/agent.py, tests/agents/test_smurf_file_emulator.py
Makes several changes to the Smurf File Emulator so that it's better for testing the bookbinder.
- Adds "timestamp quantization".  By clamping the start / stop times to integers, `np.arange` with an integer sample freq will create close to co-sampled data, even if the start / stop times are different between streams.
- Adds correct tags to the stream function
- Adds the ability to set a drop-chance, which will toss a subset of data points.
- Adds some params that tell the `stream` task to use the `stream_between` function of the streamer, instead of generating frames one-by-one, allowing for the task to run for a non-zero duration without sleeping.
This is required to properly test the bookbinder on the emulated data.
Tested by creating sample data and running it all the way through to …
=> File emulator quantization

socs/agents/ups/agent.py
Quick PR to fix some build warnings in the docs that I just noticed.
```
/home/koopman/git/socs/socs/agents/ups/agent.py:docstring of socs.agents.ups.agent.update_cache:9: ERROR: Unexpected indentation.
/home/koopman/git/socs/socs/agents/ups/agent.py:docstring of socs.agents.ups.agent.update_cache:7: WARNING: Literal block ends without a blank line; unexpected unindent.
/home/koopman/git/socs/socs/agents/ups/agent.py:docstring of socs.agents.ups.agent.update_cache:11: WARNING: Definition list ends without a blank line; unexpected unindent.
```
Tested new build.
=> Fix docs build warnings in ups agent docstring

socs/agents/hwp_pmx/agent.py
This PR implements a shutdown procedure for the HWP PMX agent.
This shows how one may use the hwp-supervisor session data to trigger a shutdown procedure, and how a shutdown might lock out specific tasks or processes until it is reversed.
This implements three additional operations:
- monitor_shutdown is a process that continuously monitors hwp-supervisor rotation action to determine whether or not a shutdown should be triggered. This will trigger a shutdown if either the action is 'stop', or it has been `no_data_timeout` since the last 'ok' action received. The action will be published to grafana, so an alarm can be set that triggers if the action is not 'ok' for a certain amount of time.
- The 'initiate_shutdown' task will set `shutdown_mode=True`, and will tell the PMX to cut power and …
=> Adds shutdown procedure and logic to HWP PMX agent

socs/agents/smurf_file_emulator/agent.py
Adds operation tags for the smurf-file-emulator.
Adds `oper` tags to the smurf-file-emulator, based on the tags from this PR: https://github.com/simonsobs/socs/pull/424/files. This has not been tested, but should be a good starting point for testing on the e2e system.
So we can have smurf operation books on the end2end system.
Not tested yet
=> adds oper tags to smurf-file-emulator

docker/pysmurf_controller/Dockerfile, socs/agents/pysmurf_controller/agent.py, tests/agents/test_pysmurf_controller_agent.py
Adds `tag` param to pysmurf-controller operations, which will append a user-provided tag to the end of the g3 stream tag.
This + https://github.com/simonsobs/sodetlib/pull/336 resolves https://github.com/simonsobs/socs/issues/385
Helpful for the scheduler to be able to append tags to streams or other sodetlib operations.
Not tested yet. This should be tested with https://github.com/simonsobs/sodetlib/pull/336 before merging.
=> adds pysmurf-controller tag params

docs/agents/acu_agent.rst, socs/agents/acu/agent.py, socs/agents/acu/exercisor.py
ACU Agent has an ability to command itself through a series of test motions, indefinitely.  The current motion type and a count of any errors are published to a feed.
This has been useful for testing SATPs at site.  It is not the most polished code but I think for completeness it would be good to merge it into main line so it be run in the main OCS account and not in my screen session... 
This evolved from an independent client code that commanded the platforms through test motions for the past few months.  But since late April it has been run, in its current form, for many hours, on the SATPs at site.
=> ACU Exercisor mode

docs/agents/hwp_pmx.rst, socs/agents/hwp_pmx/agent.py, socs/agents/hwp_pmx/drivers/PMX_ethernet.py, tests/integration/test_hwp_pmx_agent_integration.py
This adds protection mode and error monitoring to the pmx agent and adds task to clear protection mode.
With this change, the pmx agent will minitor for error and check if the pmx is in protection mode for every acq runs.
Information about errors and protection mode will be output to data along with voltage and current.
`clear_alarm()` method of the pmx agent can be used to exit the protection mode.
#455 
Tested with chwp-daq pc in UTokyo
=> Add protection mode monitoring to pmx agent

setup.py, socs/db/suprsync_cli.py, tests/agents/test_suprsync_agent.py
This moves the suprsync script in `bin` to an socs entrypoint. It also adds an additional sub-command to add files from a local directory to the suprsync db.
Since the timecode dir finalization has already been reviewed, I figured we could review this in its own PR, and then merge both together to main  once tested on the e2e system.
This is a nice user interface for checking the status of the suprsync db. The `add-local-files` command is useful for things like setting up hk sync or for the e2e testing system.
Tested locally.
=> Suprsync CLI

socs/agents/generator/agent.py
Separates generator fields into separate blocks.
Sometimes the generator is not able to provide data for certain fields, in which case we don't want those fields to be published to grafana. The current version will simply remove those fields from the block, which starts throwing errors due to block structures not matching. To fix this, this PR separates fields into different blocks since they may not be co-sampled.
Buxfix for current implementation of the generator agent.
Not tested yet
=> Separate generator fields into different blocks

requirements/testing.txt, tests/integration/test_cryomech_cpa_agent_integration.py, tests/integration/test_hwp_pid_agent_integration.py, tests/integration/test_hwp_pmx_agent_integration.py, tests/integration/test_ibootbar_agent_integration.py, tests/integration/test_ls240_agent_integration.py, tests/integration/test_ls372_agent_integration.py, tests/integration/test_ls425_agent_integration.py, tests/integration/test_pfeiffer_tc400_agent_integration.py, tests/integration/test_pfeiffer_tpg366_agent_integration.py, tests/integration/test_pysmurf_monitor_integration.py, tests/integration/test_scpi_psu_agent_integration.py, tests/integration/test_synacc_integration.py, tests/integration/test_ups_agent_integration.py, tests/integration/util.py
This does as the title says and replaces the use of the pytest plugin `pytest-docker-compose` with the plugin `pytest-docker`. 
The difference is that `pytest-docker-compose` only supports docker-compose v1, while `pytest-docker` supports v2.
This, together with #482 fixes recent issues with installing socs.
#482 introduces a pin of pyyaml (`pyyaml>6.0.1`) which `pytest-docker-compose` (which pins to `pyyaml<6`) is incompatible with.
After seeing checks run, it turns out dropping this dependency completely fixes #478 without #482.
Fixes #478.
I ran tests locally with this new plugin.
=> Replace pytest-docker-compose with pytest-docker plugin

socs/agents/lakeshore372/agent.py, tests/integration/test_ls372_agent_integration.py
Added a separate task that can change autorange settings for a 372 channel outside of the `input_configfile` task
This change is required for adding the capability to individually change this setting as well as add it to ocs-web
Tested successfully on a 372 in the lab at Yale
=> Add Autorange Task to 372 Agent

socs/agents/lakeshore372/agent.py
Fixes the inconsistencies in the doc strings for the custom pid process in the 372 agent
Resolves #491 
Hasn't been tested as it's just doctstring errors; the code already requires `custom_pid()` to be used but the doc strings mention using `start_custom_pid()` which won't work anyway.
=> Fix docstring errors for 372 custom pid process

socs/agents/suprsync/agent.py, socs/db/suprsync.py, socs/db/suprsync_cli.py, tests/agents/test_suprsync_agent.py
This adds additional stats for each suprsync archive, which are added to session.data along with hk feeds. This can be used by G3tSmurf to determine the finalization time for each archive, and for grafana monitoring.
Required for G3tSmurf to determine when an archive is complete and books can be created. Also useful for monitoring in grafana.
Tested by running the agent locally with fake data.
=> Suprsync archive stats

docs/agents/lakeshore372.rst, socs/agents/lakeshore372/agent.py
Allows the user to choose between autorange or a set resistance range for a 372 channel.
Resolves #495 
Tested in the lab on a 372 at Yale
=> LS372 Agent: Add ability in config file to set channel resistance range

socs/agents/ibootbar/agent.py
Fixes agent acq process crashing on reconnection. Continues loop on SNMP disconnect.
Resolves #492 
Tested in lab on ibootbar.
=> Fix ibootbar agent acq crashing during reconnection

socs/agents/hwp_supervisor/agent.py
Small change to the supervisor that sets the PID freq to zero when you call PmxOff
Small change just to ensure you don't leave the PID set to a weird state, and to make it more clear in grafana that things are off.
Mainly to make grafana panels look more consistent
Tested on satp1
=> Sets PID freq to 0 when PMX is turned off

README.rst
See title.
I often follow this link and it's pointing currently to the ocs image.
=> Fix link to docker hub socs image

socs/agents/wiregrid_actuator/agent.py, socs/agents/wiregrid_actuator/limitswitch_config.py, socs/agents/wiregrid_actuator/stopper_config.py
Swapping limit switch/stopper 1 and limit switch/stopper 2 to fix the bug at the site. This change can be acceptable for all the SATs.
This change is needed to correctly operate the wire grid at the site.
Actually, it should be tested at the site. To do so, however, approval of the pulling request and updating the docker-hub are necessary. This is an **_argent task_**.
=> swap LSL/LSR/ST1 <--> LSL/LSR/ST2 for the bug fix at the site

socs/db/suprsync.py
Found file trying to figure out what's going on the the LAT finalization at the site
Looks like we were adding up the non-copied files in the way the logic actually works and then weren't actually reporting it. Using this `num_files_to_copy` variable will make the logic on what's going on with the finalization time match the number of files we need to copy number. Note, this won't actually fix the current issue with the LAT times.
I haven't actually tested it because I'm not sure how
=> SupRsync Stats Bug

socs/agents/vantagepro2/agent.py
Some small changes to make sure the Vantage agent is robust to hardware dropouts. 
Unfortunately Weather station boots into a mode where it's uninitialized and returns junk data until someone holds down "Done" for two seconds... @RemingtonGerras do you have any idea if it's possible to automatically bypass this? We should also install batteries in the console regardless to try to avoid drop outs.
Makes the `acq` process attempts to re-initizlize connection on timeout
Required so `acq` can recover after hardware dropout
Tested with hardware at site
=> Small change to make vantage agent more robust to hardware dropouts

socs/agents/acu/agent.py, socs/agents/acu/drivers.py
Enables basic LAT co-rotator control and readout.  A couple of minor improvements come along for the ride.
These are fairly minor changes; there are more important fixes in the latest versions of soaculib and ocs-web. Those should be up to date to take full advantage of LAT.
This is the result of direct testing on the LAT.
=> ACU -- updates to work with LAT

socs/agents/meinberg_m1000/agent.py
This just sets the `acq` process' status to 'running' once a connection is established, just before the acquisition loop occurs.
@msilvafe pointed out the agent at site was stuck in the 'starting' state.
It hasn't been tested.
=> Set M1000 Agent acq session status appropriately

socs/agents/acu/agent.py
And also the restart_idle now simply reads the main dataset on the command interface.
The changes only matter for LAT platform; SAT operation unaffected.
=> ACU: adjustments for moving LAT corotator

socs/agents/ifm_sbn246_flowmeter/agent.py
Same as #528: Setting the acq process status to 'running' once a connection is established before the acq loop begins.
So the agent doesn't remain in 'start' mode, which triggers alarms
It hasn't.
=> set acq session status appropriately

socs/agents/vantagepro2/drivers.py
- UVI is no longer off by a factor of 10 (divided by 10)
- UVI overflow issue is fixed by adding 2**7 to negative (overflowed) values
- Changed temperature from Fahrenheit to Celsius
[Issue #531](https://github.com/simonsobs/socs/issues/531)
I ran python in terminal and created functions that take dummy input values and output the changed value. 
These functions reflected the changes I made in the agent.
There are comments in code that should be changed (instances of 'fahrenheit' to 'celsius')
=> Addressed (most of) Issue #531

socs/agents/ucsc_radiometer/agent.py
Same as #528 and #533: Setting the acq process status to 'running' once a connection is established before the acq loop begins.
So the agent doesn't remain in 'start' mode, which triggers alarms
Resolves #546 
Hasn't
=> set acq session status to running

socs/agents/lakeshore372/agent.py
Title says it all.
There isn't really a reason to restrict these to `int`. @mhasself pointed this out as he prepared ocs-web's interface for submitting params.
It has not been tested.
=> Allow floats for custom PID task arguments

socs/agents/acu/agent.py
A few important things pertinent to constant elevation scanning:
- Limit the turnaround acceleration according to the maximum jerk constraint described in the SATP ICD.
- Log the parameters passed in by the user, and computed params.  For forensic tracking on failed scans.
- Monitor key program track error bits, and state them in the log if they fire during scan.
- Return False from the Process, if it appears to have exited due to error.
- Clear Faults before starting a scan (-- and also before a go_to).
These are all to make real usage smoother, and forensic analysis possible (why didn't the scan several hours ago work?).  And the max jerk constraint basically came out because it was very easy to trigger a "Turnaround time too short" fault.
I developed this actively on SATP2.
=> Improve ACU scanning fault tolerance and logging

socs/agents/acu/agent.py
1. By passing `--ignore-axis=...`, the agent will decline to command one or more axes, and pretend that all moves on the axis succeed.  This is useful in cases where an axis needs to be disabled for some reason, but you still want to run scans and stuff.
2. The "idle stow" feature of LAT ACU requires using the command interface every minute, to prevent Survival Mode.  This renames the process that does it, and makes sure to start that process if platform is LAT type.  Can be disabled with cmdline option.
Both of these came up on LAT last week.
These changes will remove the need for me to run the LAT agent out of my user dir ... agent config should include args `--ignore-axis el` for now.
I've tested these on SATP2.
=> ACU Agent -- two features (LAT support)

docs/agents/acu_agent.rst, docs/user/installation.rst, requirements.txt, setup.py, socs/agents/acu/agent.py, socs/agents/acu/avoidance.py, tests/agents/test_acu_agent.py
The ACU Agent monitors and reports the Sun position.  If active_avoidance is enabled, it will reject non-Sun-safe moves, and even slew to safe position if idle and the Sun gets too close.  "Too close" is controllable, to some extent, through command line args.
Note this currently the changes from #554.
SATPs do not have built-in Sun Avoidance.  But we might run this on the LAT too, to have more fine-grained / easily configurable control.
I developed this on SATP2, and ran through a number of different situations.
=> ACU Sun Avoidance

socs/agents/pysmurf_controller/agent.py
Adds a general task to set tes biases to specified values, and a separate task to zero biases. Resolves #544.
Adds a needed function to the pysmurf-controller `set_biases` that lets you generally set tes biases. Also adds `zero_biases` task which can makes it easier to zero all biases from OCS web.
We need more control over TES biases from pysmurf-controller.
Not tested yet.
=> Adds general task to set TES biases

socs/agents/suprsync/agent.py, socs/db/suprsync.py
Adds routine in suprsync main function to regularly update timecode-directories for files that have not been added with the `add_file` interface.
There is currently an issue with the suprsync finalization, where timecode directories are not being added for files added by the pysmurf-monitor, since it does not use the `add_file` function in suprsync. This fixes that issue, by having the suprsync agents regularly (like every 6 hrs) add the TimecodeDir if it does not exist for any file added in the last week.
Required to fix finalization and smurf bookbinding.
Resolves #562
Tested with smurf-sync on smurf-srv20
=> Suprsync update tcdirs

socs/agents/ucsc_radiometer/agent.py
Addressing this error for the PWV agent:
`Unable to format event {'log_logger': <Logger 'ocs.ocs_agent.OCSAgent'>,
'log_level': <LogLevel=info>, 'log_namespace': 'ocs.ocs_agent. OCSAgent',
'10g_SOle': None, 'log_format': 'acq:0 CRASH: [Failure instance: Traceback: <class \'requests .exceptions .JSONDecodeError\'>: [Errno Expecting value] {"pwv": nan, "timestamp": nan}: `
I'm 10% unsure that this is truly an HTTP requests failure because I don't know if I should expect/assume a 204 error to output `nan`'s. Implementing a try/except to loop through and make the http request again. Added a `self.log.info` message to query the requests status code the next time this happens in the agent to know more.
Hasn't been tested on the flask server at the site itself.
=> PWV HTTP Requests Error 

.pre-commit-config.yaml, socs/agents/hwp_gripper/agent.py, socs/agents/hwp_pid/agent.py, socs/agents/hwp_pid/drivers/pid_controller.py, socs/agents/hwp_pmx/agent.py, socs/agents/hwp_pmx/drivers/PMX_ethernet.py
Changes to the hwp_gripper, hwp_pid, and hwp_pmx agents to improve functionality at the site
- hwp_gripper: fixed how arguments are passed to the agent and renamed a function for consistency
- hwp_pid: changed the socket communication to prevent agent crashes
- hwp_pmx: changed the socket communication to prevent agent crashes
As it is currently, the hwp_gripper agent does not work. The changes made to that agent were made to get it running. The hwp_pid and hwp_pmx agents crash if the network communication is temporarily lost. The changes made to those agents are to prevent that crashing.
All three of these agents have been running on the dev environment overnight with no issue. The changes to the hwp_gripper agent are minor and only effect how the agent is initialized. The changes to the …
=> Hwp site changes

docs/agents/pysmurf-controller.rst, docs/user/installation.rst, requirements.txt, setup.py, socs/agents/pysmurf_controller/agent.py
Adds exception for epics channel access get failure in pysmurf-controller check-state. I believe this should make the check-state function more robust by preventing the behavior seen in #575 .
Excepts caget failures in check_state
#575 
Not tested yet
=> Adds except for caget failure

docs/agents/wiregrid_actuator.rst, socs/agents/wiregrid_actuator/agent.py
Add `speedrate` argument for `insert()`/`eject()` functions in `wiregrid_actuator` agent and set the limitation of the parameter from 0.0 to 5.0.
The default value of `speedrate` is 1.0 and changing `speedrate` allows us to do fast inserting or ejecting, which is useful to check the difference between the detector responses with and without the wiregrid. Setting the `speedrate` to 5.0, the time duration for each inserting or ejecting would be about 30 sec which is three times shorter than that in default setting (`speedrate`=1.0).
**CAUTION!! \
`speedrate` > 1.0 must not be selected if elevation is not 90 deg.** 
It was tested in Kyoto using wiregrid.
=> Add `speedrate` parameter for `insert()` / `eject()` functions in `wiregrid_actuator`

socs/agents/ucsc_radiometer/agent.py
Through debugging this agent in the `daq-dev` environment, I came across a timeout exception that occurs in the radiometer agent. This won't solve our current problem, as that issue is related to the CLASS server connection. But this exception adds a bit more robustness to the agent. Also changed the ConnectionError log message to output the specific error rather than a summary.
Has been tested on the CLASS server in the `daq-dev` environment.
=> add timeout exception error and timeout vals

socs/agents/hwp_pmx/agent.py
Changed variable name to fix minor bug
The hwp_pmx agent references a variable contained within the hwp_supervisor agent. In the supervisor agent the variable name changed, but this change was not also applied to the pmx agent. This pull request changes the pmx variable to the newer convention.
Fixes a bug
https://github.com/simonsobs/socs/issues/580#event-11089174660
It has not been tested, but the pull request only changes a single variable
=> Changed variable name to fix minor bug

docs/agents/wiregrid_actuator.rst, socs/agents/wiregrid_actuator/agent.py
Fix bug in speed_rate limitation in wiregrid_actuator/drivers/Actuator.py for high speed mode.
The limitation was changed from <=1.0 --> <=5.0.
=> Fix bug in speed_rate limitation in wiregrid_actuator/drivers/Actuator.py

.github/workflows/pytest.yml, socs/agents/hwp_supervisor/agent.py
Changed monitor and spin_control processes to update the session.status to 'running'
Bugfix in response to #584. Changed the monitor and spin_control processes to update the session.status to 'running'
Fixes #584
Has not been tested, but the bugfix is simple and only changes the value of a variable
=> Changed monitor and spin_control processes to update the session.status to 'running'

socs/db/suprsync.py
Changes suprsync get_copyable_files so that doesn't include ignored files.
Changes suprsync get_copyable_files so that doesn't include ignored files.
We don't want to attempt to copy bad files.
Not tested yet
=> Suprsync shouldn't try to copy ignored files

socs/agents/acu/agent.py
Adds basic Sun-safety "policy" for the LAT, even though avoidance won't be enabled for now.  Without this the monitor_sun process just crashes.
Also makes sure that `_check_scan_sunsafe` short-circuits to True when avoidance is disabled (and to False if the map is not valid).  This means that a sun-safety policy is not needed, if avoidance is disabled.  The monitor_sun process will not be runnable, but that's ok.
LAT could not scan; this was a bug.
Tested on LAT in a few different configs.  This should not affect how SATPs run.
=> ACU: permit scans on LAT even when Sun Avoidance is not to be enabled

docs/user/installation.rst, requirements.txt, setup.py
This PR moves the `requests` package into the main dependency list.
`requests` is used by four agents now, so I think it makes sense to include in the main dependency group. Also, it was only listed as a requirement for the SynaccessAgent, which missed out on several other agents.
In a fresh virtual environment:
```
$ pip install .
$ pip freeze
attrs==23.1.0
autobahn==23.6.2
Automat==22.10.0
cbor2==5.5.1
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
constantly==23.10.4
cryptography==41.0.7
deprecation==2.1.0
flatbuffers==23.5.26
greenlet==3.0.2
hyperlink==21.0.0
idna==3.6
incremental==22.10.0
influxdb==5.3.1
msgpack==1.0.7
numpy==1.26.2
ocs==0.10.3
packaging==23.2
ply==3.11
py-ubjson==0.16.1
pyasn1==0.4.8
pycparser==2.21
pycryptodomex==3.19.0
pyModbusTCP==0.2.1
pyserial==3.5 …
```
=> Move requests package from separate group into `install_requires`

docs/agents/ups.rst, socs/agents/ups/agent.py
Break the acq process loop and exit the agent after 60 minutes. Must add `restart: unless-stopped` to docker-compose file to automatically restart the docker container everytime this occurs.
Temporary fix for UPS agent which is the biggest contributor to high memory usage among site agents. This releases that memory by exiting the agent completely, which is what we've been doing manually. A fix to pysnmp, by switching to using asyncio, will come later.
Tested in lab
=> Restart UPS Agent every 60 minutes

socs/agents/hwp_pid/agent.py
Make hwp_pid more robust
To make hwp_pid more robust, made timeout longer and sampling rate lower.
Any other suggestions of modification is very welcomed.
We observe so many timeout in satp3 hwp_pid. Especially when house keeping data rate increases (when hwp spin fast).
I would like to test the effect of this modifications.
=> Make hwp_pid more robust

socs/agents/ocs_plugin_so.py, socs/plugin.py
When trying to get PCU running, noticed that we forgot to add the PCU agent to the plugin file.
When trying to get PCU running, noticed that we forgot to add the PCU agent to the plugin file. This fixes that.
Bugfix
=> Adds HWPPCUAgent to plugin file

docs/agents/hwp_pcu.rst, socs/agents/hwp_pcu/agent.py, socs/agents/hwp_pcu/drivers/hwp_pcu.py
I realize it may not have been clear what I was saying about restructuring the PCU agent to avoid timeout locks since we still don't have any examples, so thought I'd throw it into a branch here for people to see and use if they'd like.
Restructure HWP PCU to use new lockless agent structure. I think this is a easier way to structure the agent, and should solve all of the issues that have to do with lock-acquisition, and generally make the agent more threadsafe.
Solves locking issues, and serves as an example for timeout lockless agents
Not tested
=> TimeoutLockless PCU agent

socs/agents/acu/agent.py, socs/agents/acu/avoidance.py, socs/agents/acu/drivers.py, tests/agents/test_acu_agent.py
- When the "go_to" task runs, and Sun avoidance is enabled, and the platform is already at the target position, there is a risk that the sun safety check will crash, because of the trivial trajectory.  This is now fixed.
- The ACU's ProgramTrack mode will reject points that specify el speeds that exceed the platform limit, even if there is no actual motion in elevation.  This caused confusion during testing, so now el_speed is set to 0 in the ProgramTrack data no matter what the user says.
- A new task, "go_to_named" will cause the platform to go_to a target az, el position that has been configured through the command line.  This is mostly to support ocs-web widgets ("go to Home" button) but has other applications, where a script could be written that is general but for which the "home" …
=> ACU motion fixes and "named-positions" feature

docs/agents/hwp_pmx.rst, socs/agents/hwp_pmx/agent.py, socs/agents/hwp_pmx/drivers/PMX_ethernet.py, tests/default.yaml, tests/integration/test_hwp_pmx_agent_integration.py
TimeoutLockless HWP PMX agent
In the operation of PMX at the site, we have many timeout lock errors. To avoid this error and make PMX control more robust, we modify the PMX agent in the same way as HWP PCU agent #600
I plan to do the same modification for the HWP PID agent as well.
The way I define actions may not be good. Suggestions for better coding are welcome.
Tested in PMX in UTokyo setup
=> TimeoutLock less HWP PMX agent

docs/agents/wiregrid_encoder.rst
"host" network mode is incompatible with port binding. The port binding example also shows a restriction to just accepting connections from localhost, which I don't think we want if the encoder is across the network and not running on the same machine that the wg-encoder agent is running.
The daq-satp3 deployment configs used this combination "host" mode and port binding, which was preventing the wg-encoder agent container from coming online.
The satp1 and satp3 configs have been updated to use just the non-`localhost` port binding, with no 'host' network mode.
=> Remove incompatible network_mode from example config

docs/requirements.txt, tests/dummy.txt
Fix docs build test by updating sphinx versions.
(BJK): It was failing on:
```
Running Sphinx v4.2.0
loading translations [en]... done
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/socs/envs/618/lib/python3.10/site-packages/sphinx/registry.py", line 442, in load_extension
metadata = setup(app)
File "/home/docs/checkouts/readthedocs.org/user_builds/socs/envs/618/lib/python3.10/site-packages/sphinxcontrib/applehelp/__init__.py", line 230, in setup
app.require_sphinx('5.0')
File "/home/docs/checkouts/readthedocs.org/user_builds/socs/envs/618/lib/python3.10/site-packages/sphinx/application.py", line 406, in require_sphinx
raise VersionRequirementError(version)
sphinx.errors.VersionRequirementError: 5.0
The above exception was the direct cause of the …
```
=> Update sphinx requirements version

socs/agents/hwp_pcu/agent.py, socs/agents/hwp_pcu/drivers/hwp_pcu.py
Make status check of hwp-pcu more robust
We had issue in the robustness of get_status in precious PR https://github.com/simonsobs/socs/pull/600 
Improved the robustness of the get_status by improving the read method and adding the clear_buffer.
Tested by phase compensation unit in UTokyo.
I would appreciate it if @17-sugiyama could double check.
=> hwp-pcu: more robust get_status

docs/agents/hwp_pcu.rst
Add documentation of udev rules for hwp-pcu
Motivated by https://github.com/simonsobs/ocs-deployment-configs/issues/142. We considered adding rules in https://github.com/simonsobs/ls240-drivers, but we concluded that it will be enough to document it socs.
=> add documentation of udev rules for hwp-pcu

socs/agents/acu/agent.py
Key features:
- ACU: go_to_axes patiently waits for the warning horn to sound
- ACU: suppress Sun escape (and logging) if platform not moveable
- ACU: allow more time for _run_scan to enter ProgramTrack mode
- ACU: increase overall timeout
Addresses issues reported in #617, #619, #620.  There are a few mysteries remaining but I think we should close these and get clean measurements of any new problems.
Resolves #617.
Resolves #619.
Resolves #620.
Tested on SATP1.  "Not moveable" suppression of Sun avoidance escapes was simulated with a time-based hack.
I am comfortable running this on any platform as is.
=> Fix some time-out / delay bugs in ACU agent

socs/agents/wiregrid_encoder/agent.py, socs/agents/wiregrid_kikusui/agent.py
This fixes the field name used to store 'encoder_data' in `session.data`. This should now match the documented structure.
When testing sorunlib functionality at site with satp1 I found the `session.data` didn't have the expected field that I was trying to pull 'last_updated' from.
```
{
"fields": {
"irig_data": {
"last_updated": 0,
"irig_time": 0,
"rising_edge_count": 0,
"edge_diff": 0,
"irig_sec": 0,
"irig_min": 0,
"irig_hour": 0,
"irig_day": 0,
"irig_year": 0
},
"encoder_data": {},
"timestamp": 0,
"enc_data": {
"last_updated": 1706047078.7213721,
"quadrature": [
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0
],
"pru_clock": [
152196144698317,
152196154698448,
152196164698596,
152196174698727,
152196184698875,
152196194699006,
152196204699154,
152196214699285,
152196224699433,
152196234699564, …
```
=> Fix 'encoder_data' field when storing session.data

docs/agents/hwp_pid.rst, simulators/hwp/hwp_emulator.py, socs/agents/hwp_pid/agent.py, socs/common/pmx.py, socs/testing/device_emulator.py, socs/testing/hwp_emulator.py, tests/integration/test_hwp_pid_agent_integration.py, tests/integration/test_hwp_pmx_agent_integration.py
This PR begins to implement an emulation framework for the HWP, to be used for testing HWP agent operation. Also restructures the HWP_PID to use the lockless format.
During the dev call, and while testing out HWP supervisor status at the site, there are a number of things that we still need to update in many of the HWP agents before we can reliably use them to observe. Due to the limited access to HWP hardware, a relatively realistic HWP emulator will be extremely helpful for developing changes, and testing them before testing on real hardware. This PR begins to implement this emulation, and I have tested it running against PID and PMX agents on my local development setup.
The data being returned from the emulator isn't perfect (especially since the PID interface requires some more …
=> HWP Emulation and PID agent lockless restructure

docs/agents/wiregrid_kikusui.rst, socs/agents/wiregrid_kikusui/agent.py
Update about `self.position_path`, `self.debug_log_path`, and `store_path`.
The `store_path` is used in `calibrate_wg()`, which is a function only for a test to evaluate the feedback parameters (`self.feedback_time` and `self.feedback_cut`).
- Remove unnecessary variable: `self.position_path`
- Merge `store_path` in `calibrate_wg()` function and `self.debug_log_path`
- Remove an argument of `store_path` in `calibrate_wg()`
- Add `if` when using `self.debug_log_path` in `stepwise_rotation()` function.
These are modifications just to simplify the script and make it more reasonable.
No
=> Update on the treatment of logfile and log directory for the wiregrid kikusui agent

docs/agents/hwp_supervisor_agent.rst, socs/agents/hwp_supervisor/agent.py, socs/testing/device_emulator.py, socs/testing/hwp_emulator.py, tests/agents/hwp_pid/test_pid_controller.py
Provides various updates to the HWP Supervisor required for site use.
This PR adds some changes that are necessary for the Supervisor to be run through sorunlib and the scheduler. Mainly, we needed a better way to track if a user-commanded operation has finished, and to determine if it was successful.
Currently, the supervisor is done by a fairly simple state machine, where agent tasks would put the machine in a particular state, and states could put the machine into a new state depending on the update function.
This PR modifies this a bit, by grouping states together into "Actions", based around user requests. Now, when a user runs an operation like `pid_to_freq`, instead of just setting the PidToFreq state, this will request a new Action that begins in the PidToFreq state. This action …
=> Supervisor actions

socs/agents/hwp_pcu/agent.py
Fixes race condition from callbacks in PCU agent
During HWP testing today Kyohei and I saw some strange behavior in when calling PCU agent operations through a client, which I am pretty sure are due to how [this race condition](https://github.com/simonsobs/socs/issues/607) interacts  [with the OCS timeout logic](https://github.com/simonsobs/ocs/blob/7badb58c6094fba6f1607284df3437ce20c06e91/ocs/ocs_agent.py#L818-L837). The behavior we were seeing was that anytime we called an operation through an OCS client with a timeout that wasn't None, it would return a TIMEOUT error even when successful. 
For testing, we changed the supervisor agent to not set any timeouts when interacting with the PCU agent, but I'm pretty sure this can be fixed by fixing that race condition in the agent …
=> moves callbacks to reactor in PCU agent

socs/agents/hwp_supervisor/agent.py
Some changes to HWP control logic from testing on SATP3 hardware with kyohei.
A few changes to supervisor control logic including:
- addition of PCU control into various control states
- nailing down braking logic
Tested on SATp3 hardware
=> Supervisor updates

socs/agents/hwp_gripper/agent.py
Change check range of gripper distance from 10 mm to 20 mm.
Since the actuator distance of the SATP3 is greater than 10 mm, it is helpful to allow a distance of up to 20 mm for the operation of the SATP3 gripper.
No testing is required because this is a very minor change.
=> Change check range of gripper distance

socs/agents/vantagepro2/drivers.py
Added wind chill function and report the wind chill temperature during acq process.
Above :)
[531](https://github.com/simonsobs/socs/issues/531) (continued)
Put functions into a python terminal, checked results with various online calculators.
=> Vantage windchill

socs/agents/vantagepro2/drivers.py
This scaling changes the type from an int to a float, which once published to an InfluxDB is immutable without completely removing or rewriting the measurement.
The scaling can be handled on the display end in Grafana for until a solution is found.
I'm trying to deploy an updated version of the agent to the site. The update includes changes from #539 and #550.
This'll allow resolution of all but one of the issues in #531.
This has run on site with the vantage hardware.
=> Revert UV index scaling in vantage agent

socs/agents/hwp_pmx/agent.py
Minor debug of hwp-pmx.
We need to reset the protection code (self.prot) in clear_alarm task.
This was implemented in the previous version of agent (following link), but I forgot to include this self.prot reset when we refactored the hwp-pmx agent to be TimoutLock less.
https://github.com/simonsobs/socs/blob/288fb5c2cac25d554bcfa161e6fb455b7eee1fd5/socs/agents/hwp_pmx/agent.py#L129
=> hwp-pmx: reset protection code in clear_alarm

docker/pysmurf_controller/Dockerfile
Bumps sodetlib docker version in the pysmurf-controller to include bias_wave function.
=> bump sodetlib

socs/agents/ifm_sbn246_flowmeter/agent.py
Handling the following error for the flowmeter; noticed that pump skid 1 required frequent restarts due to this:
```
2024-03-22T10:08:04+0000 acq:0 CRASH: [Failure instance: Traceback: <class 'requests.exceptions.ConnectionError'>: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
Need to implement connection error handling in agent 
Hasn't been tested at the site---currently have pump skid 1 agent with error handling running on daq-dev in case a connection error comes up soon. At the time of submitting this PR, no connection error has yet occurred.
=> error handling for flowmeter agent

docs/agents/hwp_gripper.rst, socs/agents/hwp_gripper/agent.py
- Add some documentations
- Make grip safer
- Add ungrip
https://github.com/simonsobs/chwp-discussions/discussions/17
We need to test
=> Safer grip and add ungrip

socs/agents/pysmurf_controller/agent.py
Replaces nans and +- inf in bias step quantile functions.
This should fix the issue with infs getting passed to session.data reported here: https://github.com/simonsobs/socs/issues/645
Resolves #645, which has been occasionally crashing the schedule.
I've tested running the line w/ fake data to make sure there are no typos.
=> Run nan_to_num on quantiles

docs/agents/hwp_supervisor_agent.rst, socs/agents/hwp_supervisor/agent.py
Adds a couple of tasks to the HWP supervisor that allows for enabling and disabling the HWP driver board.
One functionality missing in the supervisor agent, as described in [this discussion](https://github.com/simonsobs/chwp-discussions/discussions/19) is the ability to enable/disable the HWP driver board at the start/end of an observation, to turn off the HWP encoder LEDs. This PR adds operations that will do this, which can be put into the scheduler.
Not tested yet
=> Supervisor functionality for enabling/disabling HWP driver board

socs/agents/generator/agent.py, socs/agents/labjack/agent.py, socs/agents/lakeshore240/agent.py, socs/agents/lakeshore425/agent.py, socs/agents/pysmurf_controller/agent.py, socs/agents/smurf_file_emulator/agent.py, socs/agents/vantagepro2/agent.py
These conflict with recent ocs, where status comes in as "running" already, and "starting" is going backwards
Test failure in #663 -- I guess test system just starting using newer OCS with the session fixes / changes in it?
Just the CI.
=> Remove instances of session.set_status('starting')

socs/agents/acu/agent.py
Fix logic error in monitor_sun process, where a stale (or undefined) timestamp could be used to determine danger/warning zone. This was most likely to be activated on Agent startup, if the ACU was not reachable, on first loop iteration in monitor_sun.
Resolves #661 
Tested on satp2, where ACU is currently off.  Process did not crash and exit.
This is unlikely to cause any issue for existing installations, as the change is minor.
=> ACU: fix crash of monitor_sun when ACU not on

.flake8, socs/mibs/MBG-SYNCBOX-N2X-MIB.py
Removes `mibBuilder` from `MBG-SYNCBOX-N2X-MIB.py` which had overwritten the `mibBuilder` instantiated in `snmp.py`, thus removing the `MIB_SOURCE` path added in `snmp.py`.
The Syncbox Agent was failing due to SNMP not being able to find the new MIB. This import at the top of the MIB file was automatically generated from using `mibdump.py` to convert the ASN1 file to a .py MIB.
Tested on Syncbox agent running on `daq-dev`
=> Remove mibBuilder from MBG-SYNCBOX-N2X-MIB.py

socs/agents/hwp_supervisor/agent.py, tests/agents/test_hwp_supervisor_agent.py
Bugfixes that are related to subclassing dataclasses
This fixes the same problem that @bbixler500 addresses in https://github.com/simonsobs/socs/pull/657, however does it by replacing the inheritance of the `Base` class with the addition of a `ControlStateInfo` class that manages general state metadata such as start and last update time, and the state-name.
This fixes issues in the current code where having a dataclass subclass a non-dataclass object will overwrite the __init__ function, leaving fields undefined.
I think Bryce's method of using `kw_only=True` is a valid fix, but only works python >=3.10.
Since the mechanics of combining dataclasses and inheritance is not fully clear to me, I think its generally better to use this method even after python3.10, since the inheritance is more …
=> Removes subclassing for ControlStates

socs/agents/pysmurf_controller/agent.py, socs/agents/pysmurf_controller/smurf_subprocess_util.py, tests/agents/test_pysmurf_controller_agent.py
This PR changes pysmurf-controller operations that load TODs such that instead of running in the main process, they call out to a subprocess.
This introduces the `smurf_subprocess_util` module, and a protocol for running functions inside a twisted subprocess in such a way that a general RunCfg can be passed to it, and a general RunResult can be returned. Any operation that involves TOD data loading is modified so that the loading and analysis occurs in a subprocess rather than in the main one.
This should hopefully solve the memory leak, which I believe is coming from instances where TOD data is not being released to the system after it leaves scope. Moving TOD loading and analysis into subprocesses instead of the main one should enforce that this memory is returned to the OS when the …
=> Moves pysmurf-controller functions that load lots of data to subprocess

socs/agents/pysmurf_controller/smurf_subprocess_util.py
Logs errors in pysmurf-controller subprocess.
We are seeing that since the subprocessing change, failures in pysmurf-controller operations are not logging exceptions that are thrown (though the tracebacks are being stored in session.data). This PR adds a log of the traceback when an exception is caught in the subprocess.
See here for an  example: https://github.com/simonsobs/daq-discussions/discussions/95
Not tested yet
=> prints errors caught in the pysmurf-controller subprocesses

socs/agents/wiregrid_kikusui/agent.py
In this pull request, I changed the max current setting about the wire grid kikusui agent. It was changed from 3.0 A to 4.5 A.
The kikusui power supply itself supports 18 V-5 A max in its specification. And this change will increase the motor's max torque, so the wire grid can rotate under lower temperatures.
Now the wire grid used for SAT-MF2 has an issue in that it cannot rotate under low ambient temperature, even though the grease in its bearing has temperature resistance. When I checked the rotation directly, the rotator can move with a small additional torque support by hand. Then, to make the rotation robust, we want to change the max current setting to 4.5 A.
At the site, I changed the settings of the kikusui power supply manually, and confirmed the grid can rotate at 4.5 A max. …
=> Modification the max current setting of the kikusui agent (wire grid)

socs/agents/hwp_encoder/agent.py
This PR changes the log level of the 'Received timeout packet.' message in the HWP Encoder agent from 'error' to 'debug'. If the HWP is not spinning, this packet is expected as normal behavior.
I also add the setup that allows changing the log level via environment variable, so it can be changed in the Docker Compose config. 
When the HWP is not spinning, this packet is received every 10 seconds, filling the logs with this message. This makes it difficult to see any other messages that might be more relevant for debugging.
Not yet tested, though is a straightforward change. The log level selection is used in other agents.
=> Move HWP encoder timeout packet log to debug level

socs/agents/pysmurf_controller/agent.py, socs/agents/pysmurf_controller/smurf_subprocess_util.py, tests/agents/test_pysmurf_controller_agent.py
This PR adds quantiles for stats into session data for iv and bias step ops, and publishes them, so we can have some data quality metrics in grafana.
Adds quantiles from Rn to IV op, and Rtes, Rfrac, and Si for bias steps / bias waves ops.
We would like to be able to tell immediately from grafana if there is an issue with detector data quality.
Not yet tested. I'd like to test on satp1 or satp3 before merging.
=> Pysmurf op data quality checks

socs/agents/hwp_supervisor/agent.py
Make IBootState compatible with synaccess agent originally it was only compatible with ibootbar agent.
Make IBootState compatible with synaccess agent and add encoder timestamp
This PR addresses https://github.com/simonsobs/socs/issues/691 and https://github.com/simonsobs/socs/issues/681
https://github.com/simonsobs/socs/issues/691 and https://github.com/simonsobs/socs/issues/681
Tested in daq-dev for satp3
=> hwp-supervisor: make  IBootState compatible with synaccess.

socs/agents/wiregrid_kikusui/agent.py
Modify the max current setting of the wiregrid kikusui agent from 4.5A to 4.9A
Improve the current limitation applied the rotator motor of the wiregrid
This agent has worked at the previous max current 4.5A and this max current 4.9A should be safe according to the spec sheet. Therefore, this modification should be safe.
=> Modify the max current setting of the wiregrid kikusui agent

Dockerfile, pyproject.toml
Setuptools needs to be updated before installing some of our other packages, like soaculib, so explicitly upgrade it before installing from the requirements file. I also expect to run into issues when we build, so we pin setuptools in the pyproject.yaml like ocs [1].
[1] - https://github.com/simonsobs/ocs/pull/392
All recent builds on PRs are failing.
Docker image and wheel built locally.
=> Pin setuptools

docs/agents/hwp_supervisor_agent.rst, socs/agents/hwp_supervisor/agent.py
This PR adds a check of the ACU elevation before allowing for spinup of the HWP.
Adds ACU state information to the `HWPState` class. This state info is used by the control-state `update` function to check the ACU elevation and last update time before enabling spin-up.
Motivation is described in Kyohei's discussion here: https://github.com/simonsobs/daq-discussions/discussions/96.
This has not yet been tested! @ykyohei can we test this on one of the SATs? To test at a safe elevation, we can raise the `acu_min_el` param.
=> HWP ACU checks for spin-up

Dockerfile
This PR updates the base image to be `simonsobs/ocs:v0.11.1-1-gb6cbd88`, which is the first image after `ocs` removed several redundant base layers (see https://github.com/simonsobs/ocs/pull/397). 
This should reduce the image size for socs images.
Builds and tests have been run locally and all pass.
=> Update ocs base image to use newly reworked image

socs/agents/hwp_pid/agent.py, socs/agents/hwp_pid/drivers/pid_controller.py, socs/testing/hwp_emulator.py, tests/agents/hwp_pid/test_pid_controller.py, tests/integration/test_hwp_pid_agent_integration.py
Attempts to fix hwp pid error handling issues
Occasionally the hwp pid controller will read an error value which it does not know how to handle, which will crash the monitoring process. This PR adds handling to this specific error code.
Issue described here ([link](https://github.com/simonsobs/chwp-discussions/discussions/20))
Briefly ran changes on satp1 hardware. Error rarely occurs, so was unable to verify correct handling explicitly.
=> added handling of pid error response

socs/agents/hwp_pid/drivers/pid_controller.py
Delete initial hwp rotation direction setting of hwp_pid agent to resolve the hwp rotation direction ambiguities.
The "direction" in the hwp_pid memory register doesn't reflect the actual action of pid agent until hwp_pid.tune_freq is called. The default setting of "direction" on the agent startup lead to the ambiguity of hwp rotation direction. This PR delete the default setting. 
As long as we use `hwp_supervisor.pid_to_freq`, we can avoid this issue. https://github.com/simonsobs/socs/blob/4902d3be867b51ea77514825d5a301581fb1828b/socs/agents/hwp_supervisor/agent.py#L739-L750
However, if `hwp_supervisor.pid_to_freq` fails in the middle of its command sequence, we may still have a potential ambiguity in rotation direction, so maybe we should make it more robust? …
=> hw_pid: delete initial set_direction

socs/agents/hwp_supervisor/agent.py
This PR switches a couple lines in the brake functionality of the hwp-supervisor agent.
In the logic of the brake function I switched the order of lines so that the setting of the voltage occurs after switching the pmx to direct voltage control.
Currently the brake function of the hwp-supervisor has an argument `brake_voltage` which does not work because of a bug. To brake, the hwp uses a PMX power supply. This power supply can be configured to use an external voltage to control the output. This configuration is enabled during rotation and takes a PID feedback as an input. To brake however, this configuration is disabled and a static voltage is used instead. The issue is that while the external voltage configuration is enabled, commands to change the static voltage are ignored. Thus as …
=> HWP supervisor agent brake bugfix

socs/agents/hwp_supervisor/agent.py
Changes how the supervisor indexes iboot outlets when querying their state. This change only effects how the outlet states are reported in the `monitor` session data (actual functions using the iboot outlets are uneffected)
Subtracts one from the supplied outlet number, as the iboot outlets are indexed 0-7 while the outlet input argument is indexed 1-8.
This fix ensures that the session data is accurate. Additionally, the supervisor agent would previously crash with an index error whenever trying to use outlet 8 (which is the case for the satp2 gripper power supplies)
I tested this fix with the satp2 hwp. 
Outlet states:
Before change:
After change:
=> HWP supervisor iboot indexing bugfix

docs/agents/http_camera.rst, socs/agents/http_camera/agent.py
Add logic to handle Reolink's API token. Grabs token if doesn't already have one or lease is close to expired.
The agent grabbed a token in each loop before, reaching the limit of 20 max tokens per account.
=> HTTPCameraAgent Handle token lease and usage

socs/agents/http_camera/agent.py
- Catch `ReadTimeoutError` in HTTP requests
- Ensure all data is written to the disk before copying
- Move `pm.sleep()` to start of loop
- `ReadTimeoutError` caused agent to crash
- Sometimes `latest.jpg` would not be up-to-date if the original file is not done writing
- Noticed on acq startup that the loop runs twice right away. Moved `pm.sleep()` to start to fix.
=> Various HTTPCameraAgent Fixes

socs/agents/pysmurf_monitor/agent.py
This PR adds some protection to the pysmurf-monitor main process, to protect against sqlalchemy operational errors crashing the main loop.
- On OperationalError, this will now just set the session.degraded = True and sleep 5 sec until next iteration.
- It will not clear cached files that need to be added to the database 
- This PR also adds basic type hinting to enable type checking
Resolves #712.
This has not been tested yet. We really need to figure out how to test on a system that's not at site.
=> pysmurf-monitor main process robustness

socs/agents/http_camera/agent.py
- Move the write to file into a `try-except` block and write in chunks
- Slight change to setting `connected` for each camera
To avoid `ReadTimeoutError` during writing to file, since the response data is streamed
=> HTTPCameraAgent write file change

.github/workflows/pytest.yml
Uses the [`timeout-minutes`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) setting to reduce our maximum test run time from 6 hours to 1 hour.
If tests hang, they'll hit the 6 hour timeout. Our tests typically take 20-30 minutes to run, an hour long timeout is plenty for us and avoids hogging a runner for 5 extra hours.
Not tested.
=> Set timeout for pytest workflow to 1 hour

socs/agents/http_camera/agent.py
Another attempt at catching the exceptions in the HTTPCameraAgent. Surely this will be the last fix needed.
`requests.exceptions.ConnectionError` found in logs causing agent to crash.
=> HTTPCameraAgent Add more exceptions

socs/agents/acu/agent.py
Fixes
- #744
- #745
The fix to #744 was tested on SATP1.
The fix to #745 was not tested, but it didn't cause a syntax error and new behavior won't be _worse_ than the current co-rotator behavior... and it might just work.
=> Fix 2 ACU bugs

docs/agents/hwp_supervisor_agent.rst, socs/agents/hwp_supervisor/agent.py
Adds grip and ungrip fns to hwp-supervisor with safety checks.
This PR adds two additional operations to the HWP supervisor to grip/ungrip the HWP
For these two actions, the HWP and ACU states are first checked based on [kyohei's daq-discussion.](https://github.com/simonsobs/daq-discussions/discussions/96)
If checks pass, the gripper agent grip/ungrip operations will be called.
This is to centralize the gripping procedure and to implement safety checks.
This has not been tested yet. @ykyohei any chance we can test at site sometime soon?
=> Adds grip and ungrip fns to hwp-supervisor with safety checks

docs/agents/hwp_encoder.rst, socs/agents/hwp_encoder/agent.py
Adds a `restart` task to the agent, similarly to what is done for the hwp-gripper agent in #737. This task, when called, will remotely restart the process running separately on a beaglebone microcontroller.
Currently, any time there is a power cycle to the hwp enclosure, a remote user needs to manually ssh into the encoder beaglebone microcontrollers and restart a process on each. This is both a hassle and requires an expert's knowledge. The restart task condenses this process into a single button on OCS-Web which can be run by anyone.
This task has been tested to work on the satp2 hwp. The encoder processing portion of the code is completely unaffected.
=> HWP Encoder Update (Restart process)

docker/wiregrid_actuator/Dockerfile
The `socs/docker/wiregrid_actuator/Dockerfile` was changed in this PR to make it compatible with the Ubuntu 22.
The previous wiregrid_actuator/Dockerfile was incompatible with the recent OCS version, which is based on Ubuntu 22,  because the installation method for the actuator controller libraries (`gclib`, `gcapsd`) was changed from Ubuntu 20.
The connection test to the actuator controller has been done at Kyoto.
=> Bug fix of wiregrid_actuator/Dockerfile for Ubuntu update

socs/agents/ifm_sbn246_flowmeter/agent.py
I think the decode of the temperature data from the IFM SBN246 sensor drops the MSB here;
https://github.com/simonsobs/socs/blob/81e5916aca1442c798ead412c00cdeb8a79dd88c/socs/agents/ifm_sbn246_flowmeter/agent.py#L29
From the IO-Link process data description;
but running a 32-bit word through the existing code;
```
value='abcdefghijklmnopqrstuvwxyz123456'
_b_flow = binary[0:16]
_b_temp = binary[17:30]
print(f'_b_flow = {_b_flow}')
print(f'_b_temp = {_b_temp}')
```
gives
```
_b_flow = abcdefghijklmnop
_b_temp = rstuvwxyz1234
```
which misses the MSB of the temperature process data field (letter 'q' here).  This PR fixes that.
In my lab this makes no difference, probably because it would only matter if the temperatures were much higher.  The same is almost certainly true in the field.  This …
=> Inconsequential correction to IFM SBN246 temperature decode.

socs/agents/hwp_gripper/agent.py, socs/agents/hwp_gripper/drivers/gripper_client.py
Adds two new tasks to the agent. `alarm_group` queries the specific type of generated alarm. This function will return a value of (False, 'B', 'C', 'D', 'E') depending on the current alarm state, where the letters correspond to specific groups of alarms. `restart` remotely restarts the processes which are running separately on beaglebone microcontrollers
Currently the agent is only able to query whether an alarm is present and does not have any way to distinguish different alarms from each other. The `alarm_group` task adds more specificity to what alarms are generated. As a seperate issue, any time there is a power cycle to the hwp enclosure, a remote user needs to manually ssh into the gripper beaglebone microcontroller and restart two processes. This is both a hassle and requires an …
=> HWP Gripper Updates (Alarm group and restart processes)

socs/agents/wiregrid_tiltsensor/agent.py, socs/agents/wiregrid_tiltsensor/drivers/dwl.py, socs/agents/wiregrid_tiltsensor/drivers/sherborne.py, socs/common/moxa_serial.py
I changed the wiregrid_tiltsensor agent and moxa_serial.py in the socs/common directory.
In the wiregrid_tiltsensor, I removed the type of argument from `add_argument` and added cast of the port.
In the moxa_serial.py, I added new argument, `device=kikusui`, to the class `Serial_TCPServer`. This argument is for recognize which device the serial-to-LAN converter communicate with. The tilt sensor needs to send commands not decoded and recieve commands not encoded. This change detect the device to communicate and judge the neccesity of encoding and decoding of commands.
To debug the wiregrid_tiltsensor agent.
Resolves #716.
Tested in my lab, using a serial-to-LAN converter.
=> Debug the wiregrid_tiltsensor agent

socs/agents/cryomech_cpa/agent.py, socs/agents/cryomech_cpa/drivers.py
This PR implements error handling for the Cryomech PTC class and most of the agent, with the main goal of making the `acq()` process robust to network interruptions.
In doing this I moved the "drivers" out to their own module. That's perhaps a bit noisy overall in this PR, but the interesting diffs are separated to:
* Driver error handling implementation: 41f5f8f3fe039a597fc12521739a4274d9668863
* Agent error handling in acq process: 1470e0acec6124ba18bbb09af94dabda4a8729ac
This implementation is the one outlined in "Reconnecting in the Drivers" in #538, heavily inspired by #325.
Resolves #766.
Tested by running the agent locally with an actual Cryomech compressor. Tested the agent remains online while disconnecting the network cable from the compressor and re-establishes connection when …
=> Add error handling to Cryomech PTC drivers and agent acq process

socs/agents/hwp_pid/agent.py, socs/agents/hwp_pid/drivers/pid_controller.py, socs/testing/hwp_emulator.py
Initial attempt to fix occasional issues in reading the hwp-pid direction
Adds additional logic to handle read strings that are formatted in a non standard way.
Recently changes were pushed to the hwp-pid agent #686 which changed how response messages were processed. As an unintended consequence, a new bug surfaced when reading the rotation direction #727. From these error logs it appears as though the response message is mostly correct, but it is missing an initial 0 digit. This PR is a simple fix which will remedy this specific issue. Feedback is appreciated if the issue is more complicated than described above.
This fix has not been tested and needs to be before it is merged into main
=> hwp-pid direction read bugfix

socs/agents/pysmurf_controller/agent.py
Fix the typo of 'bg' -> 'bgs', as specified in the param decorator.
Ran into an error on satp3 due to submitting 'bg' as the argument instead of 'bgs'. See https://github.com/simonsobs/daq-discussions/discussions/118#discussioncomment-10965165.
Docstring only change.
=> Fix typo in the docstrings for bias commands

.github/workflows/deploy.yml, .github/workflows/develop.yml, .github/workflows/pytest.yml
This PR does the initial setup of code coverage reporting to codecov.io. We just set this up on ocs as well (see https://github.com/simonsobs/ocs/pull/411 and https://github.com/simonsobs/ocs/pull/414.)
See https://github.com/simonsobs/ocs/pull/411.
This gets tested in the PR and on merge. Though I've tried to avoid the issues I ran into with ocs setup.
=> Setup coverage upload to codecov

.github/codecov.yml, .github/workflows/pytest.yml, README.rst
This PR replaces code coverage reporting using coveralls.io with codecov.io. It also configures codecov.
Coveralls is often very slow to navigate, making it difficult to use. I've been migrating repos I manage off of it.
Setup already in sorunlib and ocs. Tested in #780 and when that was merged to `main`.
=> Replace coveralls with codecov

socs/agents/pysmurf_controller/agent.py
Fix typo in return string of uxm_relock.
Fix typo in return string of uxm_relock.
Misleading logs
=> Fix typo in pysmurf-controller relock function

docs/agents/acu_agent.rst, socs/agents/acu/agent.py, socs/agents/acu/avoidance.py, tests/agents/test_acu_agent.py
This supports platforms where one generally doesn't want to move az and el axes simultaneously.  When setting "axes_sequential" is enabled in acu-configs.yaml, it will perform all moves as multi-legged, separating az and el.  This applies whether Sun Avoidance is on, or not.  But special handling is applied, for case of Sun Avoidance.
Relates  to https://github.com/simonsobs/scheduler/issues/122, https://github.com/simonsobs/scheduler/pull/100.
Test case; tested on SATP1 today in sequential and simultaneous modes.
=> ACU: acuconfigs.yaml setting for forcing sequential moves

socs/agents/lakeshore372/agent.py
This removes the original `YieldingLock` class from the 372 agent. This was merged upstream as `TimeoutLock` in `ocs`.
Resolves #152.
This was tested with a 372 at Yale. The `acq()` process was left running while calling individual tasks that would cause an interaction with the `TimeoutLock`. Worked without issue.
=> Replace YieldingLock with ocs TimeoutLock

socs/agents/wiregrid_actuator/agent.py
I added 'position' data, which means the wiregrid is in the view of the telescope (`'inside'`) or out of the view (`'outside'`), in `session.data`.
This change enables to monitor the location of the wiregrid easily.
no test
=> Wiregrid Actuator Agent: Add 'position' data in `session.data`

Dockerfile, socs/common/camera.py
- Added `opencv-python-headless` dependency to Dockerfile
- Make a copy of latest file instead of creating symlink
- `opencv-python` only works for local installations, need headless version for Docker
- Symlinks not valid outside of docker container
=> RTSP Camera Agent: fix docker dependency and make copy for latest file

socs/agents/hwp_pid/drivers/pid_controller.py
Adds a timeout after setting the PID parameters. This is the last thing done after calling a spin up/down
Immediately after a spin up/down is called, the first frequency query always returns as a zero.
I believe this is because we are querying the PID controller too soon after the spin up/down command. After adding this timeout the incorrect data point is removed.
I have tested this on satp1
=> Added timeout after setting PID parameters

requirements.txt
This PR pins sotodlib to the commit just before Python 3.8 support was dropped. I also removed some duplicate entries in `requirements.txt`.
sotodlib dropped 3.8 support (see https://github.com/simonsobs/sotodlib/pull/1059), which breaks our builds here.
It'll be tested in the CI.
=> Pin sotodlib

docs/agents/ld_monitor.rst, socs/plugin.py
This makes the naming convention between the instance-id and docker compose service name consistent, which host mangers need. It also adds the explicit port mapping, which the agent needs as data gets sent to it from another device, rather than it reaching out to the device (which would require the 'host' network mode.)
We also add the agent to the plugin file so it can be launched by `ocs-agent-cli`.
Noticed these while deploying the agent on site.
Largely tested on site. The plugin part hasn't been tested yet.
=> ld-monitor: Fix conifg examples and add to plugin file

docs/agents/ld_monitor.rst, socs/agents/ld_monitor/agent.py
This removes the old `session.set_status()` calls that are automated in modern ocs. I also found another change to the configs we need, specifying UDP in the port mapping.
Ran into the status trying to go backwards when running at site:
```
2025-01-06T18:47:18+0000 startup-op: launching init_ld_monitor
2025-01-06T18:47:18+0000 start called for init_ld_monitor
2025-01-06T18:47:18+0000 init_ld_monitor:0 Status is now "starting".
2025-01-06T18:47:18+0000 init_ld_monitor:0 Status is now "running".
2025-01-06T18:47:18+0000 init_ld_monitor:0 CRASH: [Failure instance: Traceback: <class 'AssertionError'>:
/opt/venv/lib/python3.10/site-packages/twisted/internet/base.py:701:run
/opt/venv/lib/python3.10/site-packages/twisted/internet/base.py:709:mainLoop …
```
=> ld-monitor: Remove `session.set_status()` calls and define protocol in compose example

docs/agents/kikusui_pcr500ma.rst, docs/index.rst, socs/agents/kikusui_pcr500ma/agent.py, socs/agents/kikusui_pcr500ma/drivers.py, socs/plugin.py
This pull request adds a new agent to operate KIKUSUI's PCR500MA AC power supply.
PCR500MA will be used as a power source to the stimulator heater to generate radiation.
Since the device will be connected to the site ethernet and be controlled from daq-pc, it should be included in this socs repository.
Test was done using the actual PCR500MA device.
The device was connected to the lab network, and the ocs agent and client were run from a PC also connected to the same network.
Functions in the agent code was tested by checking the display and the light indicator of the device.
Torelance to the ethernet disconection was also tested by just unplugging the cable from the device.
=> Add KIKUSUI PCR500MA AC power supply agent 

socs/agents/rtsp_camera/agent.py
- Move connection to camera stream to its own function
- Continue loop instead of stopping `acq` process when snapshot fails
- Add `connected` to `session.data` and OCS feed
Resolves #809 
=> RTSPCameraAgent: connection robustness

socs/agents/hwp_supervisor/agent.py, tests/integration/test_hwp_supervisor_agent_integration.py
This adds a check to the HWP supervisor to make sure the HWP is not gripped before attempting to spin up.
This also adds tests of this behavior, to make sure that the HWP cannot spin up while gripped or grip while spinning.
This check is clearly needed, unfortunately it was missing before. From the slack messages I believe this was not attempted on real hardware.
Added tests to validate this behavior.
=> Adds checks to grip_state before attempting HWP spinup

docker-compose.yml
This temporarily disables the wgactuator image build. This should be reverted once that build is fixed.
Installation broke in a way that's causing all builds to fail. Disable until resolved.
Example of failed build: https://github.com/simonsobs/socs/actions/runs/13312323581/job/37177745465
Built locally. Build fails without this patch, and then works with the patch (though of course doesn't build the removed image.)
=> Disable ocs-wgactuator-agent build

socs/plugin.py
Agent name `DS378Agent` was wrong in `plugin.py`.
This problem prevents docker container to boot up correctly.
Tested using `ocs-agent-cli`
=> fix: wrong agent name in plugin.py

socs/agents/hwp_gripper/agent.py
Added alarm check before grip and ungrip.
Added a step to check the controller alarms before grip and ungrip to avoid silent failure of these tasks.
There was an issue that grip or ungrip silently fail when the actuator controller had an alarm. Added a step to check the alarm before grip and ungrip so that these tasks will explicitly fail and prevent subsequent inappropriate hwp operations.
https://github.com/simonsobs/chwp-discussions/discussions/25
Tested at satp3 by daq-dev. I powered off the actuator controller and caused "General controller erorr" and tested that these tasks fail when the controller has an alarm.
=> Check controller alarm before grip and ungrip

socs/agents/hwp_supervisor/agent.py
Add wait in pmx_off, add max_duration for spin up.
- In pmx_off added an option to wait and block other commands until hwp stops.
- Added max_duration for spin up. If the spin up time exceeds max_duration, supervisor calls pmx_off.
- wait of pmx_off is motivated from the scheduler. satp3 has been using pmx_off and time.sleep for safe spin down, but we would like to replace it with this. I plan to update sorunlib to use this by default.
- max_duration is for hwp instrument safety. This will avoid applying large current to motor for a long time when spin up is not successful. Typical spin up time is 7-10 mins.
Tested by daq-dev at satp3
=> hwp_supervisor: add wait in pmx_off, add max_duration for spin up.

socs/agents/pysmurf_controller/agent.py
This PR just fixes some argument ordering and method signature issues. I reordered the param decorator on `set_biases` to stay consistent with the argument ordering.
I noticed the issues while reading these docs for implementing something in sorunlib.
Not tested, mostly just changes in docstrings. No removed code.
=> Fix small docstring issues on pysmurf-controller tasks

socs/agents/suprsync/agent.py, socs/db/suprsync.py, tests/agents/test_suprsync_agent.py
This PR adds a `chmod` option to the SuprsyncFileHandler that can be used to modify permissions of transferred files.
By default, this sets the default of the suprsync agent so that it adds group-write permissions if they are not there already.
We have seen several instances of problems where level2 file deletion is not able to work properly because sometimes copied files do not give the suprsync group write permissions. This should change that, enforcing that copied files are group-writeable.
Added a test to make sure permissions are adjusted properly.
=> suprsync: add support to chmod files on transfer

socs/agents/hwp_encoder/agent.py
Add new data feed of irig time minus system time
Add new data feed of irig time minus system time to hwp encoder agent
This is to help monitoring the PTP timing state.
With this value we can easily notice that we have synchronization loss either in NTP or PTP.
This has been tested by daq-dev using hwp-bbb-a2
The minus 1 second difference is reproduced.
=> add irig_minus_sys in hwp_encoder agent

socs/agents/acu/agent.py
For LAT, adds a task to open/close the shutter.  Also reads out shutter state vars and saves them in the usual places.
Requires soaculib 0+untagged.187.g3de6ea0 ([merged yesterday](https://github.com/simonsobs/soaculib/pull/36)).
Developed on ACU simulator, with datasets set up to match snapshots from LAT ACU.
Also tested on LAT, controlling the real shutter.  Compatible with latest ocs-web shutter control widget.
=> ACU agent: set_shutter task, to open/close shutter

docs/agents/acu_agent.rst, socs/agents/acu/agent.py, socs/agents/acu/avoidance.py
- Sun avoidance, ignore_axes, named_positions, default_scan_params are all set up in the acu-configs file, now.  Sun avoidance can still be globally disabled from cmdline.  Ignore_axes can be overridden from command line. min/max el can still be overridden on command line.
- Requires latest soaculib (but soaculib will remain backwards compatible with previous agent, for a bit).
- Requires updates to agent instance args and active acu-configs.yaml.
- Small fix to sun avoidance to cast out a numpy scalar.
- Interface change; update_sun task "avoidance_radius" is now "exclusion_radius", to match all other usage.  This arg wasn't exposed to ocs-web and likely has never been used by anyone.
This agent version will not work without the latest soaculib …
=> ACU Agent: take most configuration from the acu-configs.yaml

docker/pysmurf_controller/Dockerfile
Install `sodetlib` in the `pysmurf-controller` docker image and bypass the `sodetlib` docker image.
Remove the `sodetlib` docker to simplify the docker inheritance hierarchy. Corresponding PR on `sodetllib`: simonsobs/sodetlib#460. 
Built the docker image with these changes.
=> Install sodetlib in the pysmurf_controller docker.

.flake8, docs/agents/ibootbar.rst, socs/agents/ibootbar/agent.py, socs/mibs/IBOOTBAR-MIB.py
Make ibootbarAgent compatible with legecy ibootbar
Make ibootbarAgent compatible with legacy ibootbar. There are differences in SNMP version, MIB. This PR supersedes https://github.com/simonsobs/socs/pull/860.
This legacy iBootBar (iBB-N20) is used in satp3, we tried to swap the iBootBar with agent compatible device, iBoot PDU, but it turned out that it's physically not easy to do. Therefore, we modify the ibootbarAgent to be compatible with legacy ibootbar.
Tested by daq-dev. Tested this works for legecy ibootbar, also confirmed this works for iboot-pdu.
One weird point is that the agent tasks works on legacy ibootbar but I see the following timeout failure in log.
> 2025-04-22T20:19:59+0000 start called for acq
> 2025-04-22T20:19:59+0000 acq:0 Status is now "starting".
> …
=> Make ibootbarAgent compatible with legacy ibootbar

socs/agents/acu/agent.py, socs/agents/acu/drivers.py, tests/agents/test_acu_agent.py
After it stops uploading points, generate_scan waits for the az to settle at (a) the last commanded position and (b) at velocity zero.  Once those conditions are met, the process exits.  Previously there was just a flat 10 second wait.  There were cases observed where this wasn't long enough.
This does break fromfile_scan.  Sorry.  That's not used in observations but it's useful so I will get it working again, soon.
Resolves a crash seen on SAT where a scan ends, and immediately a new Preset position is commanded (while ProgramTrack is still settling down); the ACU seems to get confused and approach the new target very slowly, which times out the go_to state progress checker.
Tested extensively on simulator and also on SATP3 just now.  Behaves as desired.
=> ACU Agent: generate_scan waits for settling, before exiting

docs/agents/meinberg_syncbox_agent.rst, socs/agents/meinberg_syncbox/agent.py
Update the syncbox agent to handle conversion of strings into floats for various OIDs, standardizing units to microseconds.
Also adds `--sample-period` as a parameter.
Resolves #844 
Tested on daq-dev
=> MeinbergSyncboxAgent updates

socs/agents/hwp_supervisor/agent.py
Add estimate of rotation direction to HWPSupervisor.HWPState
Estimate the absolute rotation direction from pid_state and control_state and add estimated direction to HWPSupervisor.HWPState
Need to merge https://github.com/simonsobs/ocs-deployment-configs/pull/436 to have correct rotation direction estimate.
The real time absolute rotation direction estimate is necessary for wiregrid time constant measurement https://github.com/simonsobs/sorunlib/pull/179
Need to test
=> Add estimate of rotation direction to HWPSupervisor.HWPState

socs/agents/pysmurf_controller/agent.py
We found that the `restart_rssi` action fails on a slot that is actually locked-up because this prevents it from instantiating a pysmurf instance, which we had overlooked. This fix bypasses that interface by sending the command directly via EPICS.
Tested on a locked up slot on the LAT.
=> fix(pysmurf_controller): Bypass smurf instance for RSSI restart.

socs/agents/suprsync/agent.py
This PR changes the default `--chmod` argument passed to rsync within the suprsync agent to 'g+rwX,o+rX', which ensures files are group writable and world readable.
Resolves #871.
I tested setting this argument via the SCF on the LAT SMuRF servers. It resulted in changing the top level directory permissions from `drwxrwx---` to `drwxrwxr-x`, which is what we want.
=> suprsync: Change default chmod to set world-readable

docs/agents/acu_agent.rst, socs/agents/acu/agent.py, socs/agents/acu/hwp_iface.py, tests/agents/test_acu_agent.py
Using the ``hwp_interlocks`` configuration block, the Agent can be asked to monitor state in an HWPSupervisor agent, and use that information to restrict motion in specific axes.
When configured, the Agent's `monitor_hwp` process queries a particular HWPSupervisor instance, to learn the grip and spin state of the HWP.  It combines that information with the current elevation (or range of elevations required for some move) to determine whether a requested motion should be permitted.
These changes complement the HWPSupervisor's interlocks that prevent HWP grip and spin state changes, based on platform position. 
This has been tested extensively with ACU simulator and a dummy HWPSupervisor agent.  Two development versions were tested briefly on real platform, along the way.
=> ACU: motions can be constrained by the HWP state.

socs/agents/acu/agent.py
`go_to` will now accept `az=None` and/or `el=None`, in which case the mode for the axis will not be changed.  This is an interface change, but the behavior is backwards compatible with current common usage.
This is required for star camera surveys, where it is desirable to command azimuth moves while either holding elevation in Stop, or in Preset.
Tested with ACU simulator from soaculib.  Interface tested with current ocs-web (which does not propagate az=null, el=null) and an [updated ocs-web](https://github.com/simonsobs/ocs-web/pull/72) that can activate the feature.
=> ACU: support passive axes in go_to

socs/agents/hwp_supervisor/agent.py
This sets a longer timeout for the grip and ungrip commands to execute (12 minutes, and 1 minute, respectively) from the supervisor agent.
Resolves #882.
Not yet tested.
=> hwp-supervisor: Set longer timeout for grip commands

socs/agents/acu/agent.py
In cases where we check the ACU reply text to see if it indicates success, check against a short list of known "OK_responses".
This corrects a bug that makes the ACU Agent from #880 totally unusable at the site.
Most ACU commands return the success text "OK, Command executed."  But some say "OK, Command send."  Recent evolutions in soaculib and socs ended up using one of those latter commands, which prevented the agent from believing it had commanded successfully.
Tested moves and scans on the ACU simulator, after updating it to return the second OK response, like a real ACU.
=> ACU Agent: fix bug that prevents go_to

socs/agents/smurf_crate_monitor/agent.py
Add a task to disable a smurf slot.
This adds a task to the `smurf_crate_monitor` agent called `deactivate_slot` which allows turning off a specific slot within the smurf crate.
SATp3 weather stow procedure involves closing their air hatch to their ATCA crates. Current the signals are shutoff but the boards are not powered off before the hatch is closed. To prevent thermal issues its better to power off the slots before closing the hatch which this task allows.
I haven't tested this yet, I would like to test it on one of the site crates.
Tagging @samdayweiss, and @tpsatt to let them know I'm adding this in.
=> Add ability to deactivate slot in smurf crate

socs/agents/hwp_supervisor/agent.py
Add enc_freq timestamp to resolve the issue in ocs-web.
Add tolerance in acu elevation check so that we don't need to manually add tolerance in config.
This resolves https://github.com/simonsobs/socs/issues/788 and https://github.com/simonsobs/socs/issues/789
Tested at daq-satp3.
=> Hwp supervisor: Add enc_freq timestamp and tolerance in acu elevation check

socs/agents/stimulator_thermometer/agent.py
Changed the position of `publish_to_feed` so that `acq` can also publish cold-junction temperatures of thermocouple amplifier.
Previously cold-junction temperatures were not published to feed because of a mistake in the location of the `publish_to_feed`.
This PR fixes the problem.
Not tested yet.
=> fix: publish cold junction temperature to feed

socs/agents/acu/agent.py
Read out the built-in tiltmeter.  This requires a bunch of new code because the tiltmeter reports stale (repeated) data when the platform is moving.
LAT team wants these fields recorded to help understand LAT pointing behavior.
Tested on simulator.  Ran it at site today.
=> ACU: read out the LAT tiltmeter

socs/agents/acu/agent.py
New task for a couple of weird LAT things.
"Stow" mode is where the LAT points down and a lock pin is inserted.  The PLC can even do this automatically in some cases.  This makes it possible to recover from that, through the agent.
The "ElSync" mode for co-rotator might not be used in the long run but this will make it possible to test that in an automated way.
Tested against the simulator.  This needs to be tested on the real platform but I propose that including it in the next version of the agent is a minimally disruptive way to approach that.  The present changes won't affect anything that is otherwise working ok in the agent.
=> ACU Agent: new "special_action" task for unstow and elsync

docs/agents/acu_agent.rst, socs/agents/acu/agent.py
- Redoes logic for mapping ACU field names into OCS feed block and field names.  This is clearer and includes some helpful log messages.
- Adds two new status blocks with some missing LAT info (pointing correction status and ACU Sun Avoidance)
The current ACU agent won't run because of a missing entry in MONITOR_STRUCTURE.
Debugging that led to clearer code for navigating the map from ACU field name to OCS block / field name.
While debugging that, realized some missing fields from LAT ACU that we should probably be storing.
This is running at site now -- these changes are necessary since the current published ACU agent has a bug.
=> ACU Agent: new LAT datasets

.github/workflows/deploy.yml, .github/workflows/develop.yml, .github/workflows/pytest.yml, .github/workflows/test-build.yml
This PR fixes recent [failed](https://github.com/simonsobs/socs/actions/runs/16756704650/job/47441153631) [actions](https://github.com/simonsobs/socs/actions/runs/16754279029/job/47432476058) in PRs.
Something in the way `docker compose build` works seems to have changed in the Actions environment. The builds are happening in parallel (which I think has been true since buildx was introduced), but they load metadata about their base images first, and since most of the images defined in the compose file depend on the first image built, this is failing, since it doesn't exist yet.
We fix that by just building the base `socs:latest` image directly with a `docker build` first, then running `docker compose build`. This runs the build for `socs:latest` twice, but the second time it just uses all …
=> Fix failing docker builds in Actions workflows

socs/agents/srs_cg635/agent.py, socs/agents/srs_cg635/drivers.py
Add ValueError handling to agent process. Attempts calling the individual driver functions individually if the combined function fails.
Error found when agent deployed to site.
Traceback from Loki logs:
```
2025-08-04 21:32:46.270	
2025-08-04T21:32:46+0000 acq:1 CRASH: [Failure instance: Traceback: <class 'ValueError'>: not enough values to unpack (expected 4, got 3)
2025-08-04 21:32:46.270	
/opt/venv/lib/python3.10/site-packages/twisted/python/threadpool.py:269:inContext
2025-08-04 21:32:46.270	
/opt/venv/lib/python3.10/site-packages/twisted/python/threadpool.py:285:<lambda>
2025-08-04 21:32:46.270	
/opt/venv/lib/python3.10/site-packages/twisted/python/context.py:117:callWithContext
2025-08-04 21:32:46.270	
/opt/venv/lib/python3.10/site-packages/twisted/python/context.py:82:callWithContex …
```
=> SRS CG635 Agent ValueError handling

socs/agents/acu/agent.py
Fixes a bug where the timestamp was not properly stored for comparison with the last reading.  This led to duplicate data (including timestamp) being stored for the 'status' info.  This has caused bookbinding difficulties for the past few days of SAT data, though it's fairly easy to work around it.
This bug became relevant due to recent changes that increased the storage rate of status data to 20 Hz from 0.5 Hz.
I took this opportunity to reorganize and test the "previous vs. current" comparisons on each status read.
Tested all changes, for SAT and LAT-like data stuctures, using the ACU simulator server.
=> ACU: do not store duplicate status data

socs/agents/lakeshore425/agent.py
Implement auto reconnection to ls425 agent,
satp3 ls425 had intermittent usb connection issue.
```
2025-09-10T15:58:15+0000 acq:1 CRASH: [Failure instance: Traceback: <class 'serial.serialutil.SerialException'>: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2025-09-10T16:04:49+0000 acq:4 CRASH: [Failure instance: Traceback: <class 'serial.serialutil.SerialException'>: write failed: [Errno 5] Input/output error
```
tested at satp3 and confirmed that it successfully reconnect.
```
2025-09-10T22:03:21+0000 acq:1 Status is now "running".
2025-09-11T15:17:53+0000 Decive reports readiness to read but returned no data. Reconnect to LS425.
2025-09-11T15:17:53+0000 Could not connect to LS425. Retrying after 30 sec... …
```
=> Auto reconnection of Lakeshore 425 agent

socs/agents/pfeiffer_tc400/drivers.py, tests/integration/test_pfeiffer_tc400_agent_integration.py
Changed the expected response of the turbo in the `unready_turbo` driver call.
When the turbo receives the `unready_turbo` command it response with a `PFEIFFER_FALSE` (`000000`) and not a `PFEIFFER_TRUE` (`111111`). We assumed it would respond the opposite, so our check of if the function succeeded always incorrectly returned a failed state. We fixed this for the `turn_turbo_off` command but forgot this call.  
This specifically was not tested but the `turn_turbo_off` fix was tested. Indeed when I looked at the agent logs I see that the "setting ready state failed` now instead of the turn off failure.
=> Fixed expected turbo response to 'unready_turbo'

socs/agents/acu/agent.py, socs/agents/acu/drivers.py
Adds type 2 and 3 scans to the ACU agent
* Add functions to generate type 2 and 3 scans
* Modify `generate_scan` to allow for these scans
*  Modify `set_scan_parameters` to also set `el_freq` for type 3
Enables the use of these new scan types for the LAT.
This is needed for ISO.
Testing by running the ACU agent out of my homedir on site computing.
Scans ran successfully.
=> feat: add type 2 and 3 scans to generate scan
