simonsobs/socs

socs/Lakeshore/Lakeshore372.py
socs/simulators/ls372_simulator.py

I've added the code for a 372 simulator and edited one line of Lakeshore372.py so that it doesn't strip the last two characters of responses (line 234)

Add 372 simulator

---

requirements.txt
socs/util.py

We wound up with a state that the documentation build is fixed on this branch, but not in master. Going to just merge this, since it's working and looks good.

Fix RTD build related to new mysql imports

---

agents/pysmurf_monitor/pysmurf_monitor.py

Quick fix to make sure numpy files have correct extension. This should fix bug with copying numpy files over.

Fixed pysmurf monitor numpy bug

---

socs/Lakeshore/Lakeshore372.py

Curve upload takes any available points in calibration file

---

Dockerfile

This PR bumps the base OCS Docker image to version v0.7.0-37-g488bc7c-dev. 
We're in particular need of the fix from https://github.com/simonsobs/ocs/pull/164, but we will benefit from several other fixes as well.
This still needs more testing, however the M1000 Agent is currently in a broken state and needs this patch.

Catch up to latest ocs -dev version tag

---

agents/lakeshore240/LS240_agent.py
agents/lakeshore372/LS372_agent.py
docs/agents/lakeshore240.rst
docs/agents/lakeshore372.rst

This PR adds the latest measurements from the acq Processes for each Lakeshore Agent to the Process' `session.data` object.
Allows most recent data to be queried easily in OCS clients.
Built and ran with either a 240 simulator or actual 372 in the lab at Yale and viewed with ocs-web.

Lakeshore session.data

---

agents/bluefors/bluefors_log_tracker.py

Adds the new fields present in status logs output by the new beta software for the DR.
New status fields weren't in the regex patterns.
fixes #47
Still needs testing. Either build an image, or use `grumpy.physics.yale.edu/ocs-bluefors-agent:beta`.

Add new status log fields from beta software

---

Dockerfile

Title says it all. Catch up to the latest ocs release, v0.7.1, which was made today.
Get all the bug fixes and crossbar reboot robustness changes from v0.7.1.
socs images not yet tested.

Bump ocs base version to v0.7.1

---

socs/agent/smurf_recorder.py

This is a small fix to handle errors in the `read_stream_data` function without crashing the streamer. It also changes the smurf-recorder so that `read_stream_data` is only run if there are monitored channels.
Solves #126 .
Tested by running on the k2so system, testing with a sequence of commands that was causing the sample_rate to be nan consistently.

Handle nan in smurf_recorder read_stream_data

---

.github/workflows/develop.yml
.github/workflows/pytest.yml

v3.0.0 of coveralls-python now requires `--service` be specified for things to
work with Github Actions. See [1].
[1] - https://github.com/TheKevJames/coveralls-python/issues/251
Coverage reporting broke on the last commit.
This PR/branch successfully ran the coverage reporting.

Update coveralls command for v3.0.0

---

agents/smurf_recorder/smurf_recorder.py
socs/agent/smurf_recorder.py

Changes consist of:
1. Check if socket is open before trying to create G3Streamer to
minimize log_fatals
2. Change some info statents into debug, and some debug statements to
info
3. Discards G3PipelineInfo frames to fix stream-id-less file on startup
bug.
This fixes some small bugs in the smurf-recorder and makes it easier to monitor during operation. Mainly did this in order to further debug issue #78, but this should also resolve #112.
Tested at UCSD by hammering while the smurf-recorder was running.

Add some quality of life improvements to smurf-rec

---

agents/pysmurf_monitor/pysmurf_monitor.py

Fix bug that prevents npy files from being archived
Change the pysmurf monitor to check the md5 sum of the fixed path.
Allows npy files to be archived correctly.
Tested on the princeton smurf-server.

Fix bug that prevents npy files from being archived

---

Dockerfile

Follow the OCS update (https://github.com/simonsobs/ocs/pull/193) to Ubuntu 20.04 based images.
See https://github.com/simonsobs/ocs/pull/193.
Unit tests pass. Still needs testing in labs.

Update to Ubuntu 20.04 based ocs image

---

agents/tektronix3021c/Dockerfile
agents/tektronix3021c/tektronix_agent.py
docs/agents/tektronix3021c.rst
docs/conf.py
docs/index.rst
socs/agent/tektronix3021c_driver.py

Created an agent for the Tektronix3021c AWG to be used for vibration testing.
New agent for highbay AWG.
Agentify vibration Tests.
I have used this agent to run vibration tests on SAT1.

New Tektronix3021C AWG agent.

---

agents/scpi_psu/scpi_psu_agent.py
agents/tektronix3021c/tektronix_agent.py
socs/agent/prologixInterface.py
socs/agent/prologix_interface.py
socs/agent/scpi_psu_driver.py
socs/agent/tektronix3021c_driver.py

This makes some changes so that the PSU and Tektronix driver code can both inherit from a common `GPIBInterface`. This GPIB interface is based on the `PrologixInterface` class. 
There was a fair bit of duplicated code among these various classes. This is an attempt to simplify that interface and reduce the amount of duplicated code before another Prologix device gets integrated here. Since I'm not too familiar with the hardware, I'm not sure if the `GPIBInterface` could be eliminated in favor of putting everything in `PrologixInterface`. But maybe there is some distinction to be made here.
I removed some outdated commented out code, some related to the GPIB like functionality in the PrologixInterface, and some related to verbosity of the `tektronixInterface` class. It didn't look like it …

Prologix interface inheritance

---

agents/lakeshore372/LS372_agent.py
docs/agents/lakeshore372.rst

Added the functions set_still_heater() and get_still_heater() to LS372_agent.py so that LS372 clients can successfully set the still heater still power (as opposed to the still heater manual power...a different thing) and can then check that it was set correctly.
set_still_heater() takes one argument (output), which is the percentage of the still heater power and must be between 0 and 100. 
get_still_heater() takes no arguments.
Solves the problem of set_heater_power() being the only way to set the still power, which isn't good because it sets the still heater manual power instead of the still heater still power. Also provides a method (get_still_output) for displaying the current still heater still power using session.data via get_still_output.status().
I tested this change by writing a …

Added set_still_heater() and get_still_heater() to LS372 agent

---

agents/lakeshore372/LS372_agent.py
docs/agents/lakeshore372.rst
socs/Lakeshore/Lakeshore372.py

Add an option to enable logging the 372's sample heater, typically used to servo a DR. The addition comes in the acq process. Since you might not even be using the sample heater on a device though, we don't want to always query it. Adding `[--sample-heater, True]` to the Agent's argument list will enable.
This value is helpful to understand what your servo is doing.
In use at Yale.

Record LS372 Sample Heater

---

agents/pfeiffer_tc400/pfeiffer_tc400_agent.py
agents/pfeiffer_tc400/pfeiffer_tc400_driver.py
docs/agents/pfeiffer_tc400.rst
docs/index.rst

Some feedback for #149. Mostly it was formatting changes for proper parsing in Sphinx.

Make formatting adjustments for docs

---

docs/agents/bluefors_agent.rst

Small update to the docs to provide a more sensible starting point when setting up a new configuration on Windows.

Update bluefors agent docker config example

---

agents/smurf_crate_monitor/smurf_crate_monitor.py

Some bug fixes to help Shawn run the smurf-crate-monitor at SLAC.
A few small bug fixes which are necessary to run the smurf-crate-monitor on certain ATCA crates.
Fixes bugs in the smurf-crate-monitor.
Tested running the agent with changes at SLAC.

crate-monitor bugfixes

---

docs/conf.py

We've made some changes to the OCS conf.py file for the Sphinx docs that would be nice to have here too. This just catches us up.
This PR configures source ordered autodocs and the viewcode extension.

Catch up with recent docs conf.py changes in OCS

---

Dockerfile

Just updating the base OCS image to the latest version, mainly to get the param decorator.

Update ocs base image to v0.8.0-83-g13be6e8-dev

---

agents/acu/acu_agent.py
agents/acu/scan_helpers.py
docs/agents/acu_agent.rst

This updates the ACU Agent docs and docstrings to bring them inline with the new recommended best practices from the [OCS docs](https://ocs.readthedocs.io/en/develop/developer/agents.html#documentation).

Standardize ACUAgent docs

---

agents/lakeshore372/LS372_agent.py
docs/agents/lakeshore372.rst
socs/Lakeshore/Lakeshore372.py
tests/agents/test_ls372_agent.py

Update the 372 Agent docs to follow the new [documentation guidelines](https://ocs.readthedocs.io/en/develop/developer/agents.html#documentation) in OCS.
Establish an example in socs for documentation standards. Also the 372's docs were the primary motivation for writing the guidelines, so good to get them updated.
Not yet tested, though definitely needed now with new param decorator usage.

Standardize LS372Agent docs

---

agents/pysmurf_controller/pysmurf_controller.py
docs/agents/pysmurf/pysmurf-controller.rst

Docs standardization and a much needed update.

Standardize and update pysmurf-controller docs

---

agents/pysmurf_monitor/pysmurf_monitor.py
docs/agents/pysmurf/pysmurf-monitor.rst

Standardize pysmurf monitor docs

---

agents/pysmurf_archiver/pysmurf_archiver_agent.py
docs/agents/pysmurf/pysmurf-archiver.rst

Standardize Pysmurf Archiver docs

---

agents/bluefors/bluefors_log_tracker.py
docs/agents/bluefors_agent.rst

Hack day updates to Bluefors Agent Documentation.

Standardize BlueforsAgent docs

---

agents/cryomech_cpa/cryomech_cpa_agent.py
docs/agents/cryomech_cpa.rst

Standardize CryomechAgent docs

---

agents/labjack/labjack_agent.py
docs/agents/labjack.rst

Standardize LabJack docs

---

agents/lakeshore240/LS240_agent.py
docs/agents/lakeshore240.rst
socs/Lakeshore/Lakeshore240.py

Update the 240 docs. Could really probably use more work on the driver end, but Agent docs are updated with new formatting.

Standardize LS240Agent docs

---

agents/bluefors/bluefors_log_tracker.py
agents/cryomech_cpa/cryomech_cpa_agent.py
agents/labjack/labjack_agent.py
agents/lakeshore240/LS240_agent.py
agents/meinberg_m1000/meinberg_m1000_agent.py
agents/pysmurf_archiver/pysmurf_archiver_agent.py
agents/pysmurf_controller/pysmurf_controller.py
agents/pysmurf_monitor/pysmurf_monitor.py
docs/agents/bluefors_agent.rst
docs/agents/cryomech_cpa.rst
docs/agents/fts_agent.rst
docs/agents/labjack.rst
docs/agents/lakeshore240.rst
docs/agents/meinberg_m1000_agent.rst
docs/agents/pysmurf/pysmurf-archiver.rst
docs/agents/pysmurf/pysmurf-controller.rst
docs/agents/pysmurf/pysmurf-monitor.rst
docs/agents/smurf_recorder.rst
socs/Lakeshore/Lakeshore240.py

Full collection of the documentation updates from Friday's documentation hack day.
Update the documentation to meet new guidelines.
Untested other than documentation build tests.

Hack day Agent docs standardization changes

---

agents/lakeshore372/LS372_agent.py
tests/agents/test_ls372_agent.py
tests/integration/test_ls372_agent_integration.py

Added new functions for controlling the LS372
Functions added:
get_excitation()
set_resistance_range()
get_resistance_range()
set_dwell()
get_dwell()
Fixes issue #36 and improves agent for use in testbeds
All functions tested with a LS372 during a cooldown here at Cornell. No issues found.

Ls372 more functions

---

agents/chwp/hwpbbb_agent.py

very small fix on hwpbbb agent. add type=int for port number

---

agents/labjack/labjack_agent.py
docs/agents/labjack.rst

No idea how this was running so long without being detected, but it seems like there are a few bugs in the labjack code that was causing us trouble when updating and moving things to gir at UCSD.
- Sets `--active-channels` to `nargs='+'` so that you can specify channels manually
- Adds the `--mode`  argument which didn't exist before
- Fix typo in docs
Tested at UCSD

Labjack bugfixes

---

Dockerfile
agents/pysmurf_controller/Dockerfile

Bump base docker images:
- ocs base image to v0.9.0 for socs image build
- sodetlib base image to v0.3.0 for pysmurf-controller image build
Update to get the new so3g G3SuperTimestream update.
Not yet tested.

Update ocs and sodetlib base versions

---

socs/db/suprsync.py

Forgot to add the ssh-key into the suprsync rsync command.
Adds ssh-key to suprsync rsync command
Needed to rsync to remote host
Tested and running at ucsd

Can't believe I forgot the ssh key

---

.github/workflows/deploy.yml
.github/workflows/develop.yml
.github/workflows/pytest.yml
Dockerfile
README.rst
agents/smurf_stream_simulator/smurf_stream_simulator.py
pyproject.toml
requirements.txt
requirements/testing.txt
setup.py
socs/agent/smurf_recorder.py
tests/agents/test_smurf_recorder.py

Following https://github.com/simonsobs/ocs/pull/243, this PR sets up socs to build and deploy the package to PyPI.
Adding another package to the list of SO DAQ python modules now published to PyPI. Hopefully makes installation easier for end users.
I've built and installed the wheel locally, and published a release candidate to PyPI already: https://pypi.org/project/socs/
The workflow hasn't been fully tested yet, but it is a copy of the working OCS workflow changes.

Build and Deploy socs to PyPI

---

.github/workflows/develop.yml
.github/workflows/pytest.yml
tests/.coveragerc
tests/agents/test_cryomech_cpa_agent.py
tests/agents/test_fts_aerotech_agent.py
tests/agents/test_hwpbbb_agent.py
tests/agents/test_ls240_agent.py
tests/agents/test_ls425_agent.py
tests/agents/test_meinberg_m1000_agent.py
tests/agents/test_ocs_plugin_so.py
tests/agents/test_pfeiffer_tpg366_agent.py
tests/agents/test_pysmurf_archiver.py
tests/agents/test_pysmurf_controller.py
tests/agents/test_pysmurf_monitor.py
tests/agents/test_scpi_psu_agent.py
tests/agents/test_smurf_crate_monitor.py
tests/agents/test_smurf_stream_simulator.py
tests/agents/test_synacc.py
tests/agents/test_tektronix_agent.py
tests/agents/test_vantage_pro2_agent.py
tests/integration/test_ls372_agent_integration.py
tests/test_snmp.py
tests/test_util.py

This PR sets up a bunch of skeleton testing files for the Agents which simply import the Agents. This is to get an accurate assessment of the total coverage across all the Agents and the socs library.
My focus is on Agents we're going to field, so I'm explicitly excluding some code from coverage that I don't care to test at the moment, like the Lakeshore370 and Lakeshore336 Agents, which both are only used in labs. PRs for tests on these are certainly welcome, I'm just not going to prioritize it.
Some other Agents that are left out at the moment that are difficult to test:
- ACU Agent - This needs the soaculib library, which isn't public at the moment.
- Labjack Agent - This one we could probably do, but we'll need to setup and install the driver module in the CI environment. I'll leave …

Expand base test coverage for agents

---

.github/workflows/develop.yml
README.rst
requirements/testing.txt
setup.py

Add dependencies so that testing against the built wheel works in the CI pipeline and releases are published to PyPI.
Also add wheel build and test to commit on `develop`, that way we catch these things in the future, but also don't build the wheel and run tests again on every commit/PR.
The recent [v0.3.0 release build](https://github.com/simonsobs/socs/runs/5208413096?check_suite_focus=true) didn't work. I had tested the workflow prior to making the changes in #245 and didn't realized some dependencies were missing for testing.
Tested the process locally, and tested on a commit here: https://github.com/simonsobs/socs/runs/5218246419?check_suite_focus=true

Fix CI Wheel Builds

---

.github/workflows/test-build.yml
agents/pysmurf_archiver/Dockerfile
agents/suprsync/Dockerfile

Add an `apt-get update` to package installation in the archiver.
Also add a small workflow for testing the docker builds on PRs. This'll ensure we catch future breakage before merging into `develop`.
`develop` builds are breaking right now due to this causing an error in the build process.
Tested the build runs successfully with this patch locally.

Fix pysmurf archiver docker build and test future builds on PRs

---

agents/pysmurf_monitor/pysmurf_monitor.py

Another minor bugfix for the pysmurf monitor that we're currently running with at UCSD. G3-files are now also saved through the pysmurf monitor, and that metadata doesn't specify the format.
Small bugfix to pysmurf-monitor.
Required for suprsyncing timestreams.

Small bugfix for pysmurf monitor

---

agents/meinberg_m1000/Dockerfile
agents/meinberg_m1000/meinberg_m1000_agent.py
docs/agents/meinberg_m1000_agent.rst
socs/snmp.py

Fix some small typos, the location of MIBs within the container, and add version support to the M1000 Agent.
While configuring the site M1000 I ran into a few things, detailed in #273 and #274, as well as the small typos in the docs that became evident during setup on a fresh OCS system.
Fixes #224.
Fixes #274.
I've run this new Agent on with an M1000 configured for all three versions of SNMP.

Add SNMP version support to M1000 Agent and fix other bugs

---

docs/index.rst
docs/user/sequencer.rst

This PR documents the setup of the SO Sequencer, nextline. There are perhaps still a few things to smooth out from the user perspective, but this should be functional.
Enable lab use of the sequencer.
Resolves #267.
Tested instructions locally, able to startup nextline on localhost. I based the guide on setup done for the end to end testing.

Write sequencer docs page

---

docs/api.rst
docs/index.rst
socs/agent/moxaSerial.py
socs/agent/pmx.py
tests/agent/test_moxaSerial.py
tests/agent/test_pmx.py

This pulls out `moxaSerial.py` and `pmx.py` from #157, adds testing, and makes some small modifications to the way encoding/decoding the messages works.
#269, #183, and #157 all use `moxaSerial.py`, and #183 and #157 both use `pmx.py`. These submitted Agents should all use the same source for this.
To update your code you will need to update imports, and usage of `Serial_TCPServer.write()`. The new imports will be:
```
from socs.agent.moxaSerial import Serial_TCPServer
from socs.agent.pmx import PMX, Command
```
(Note that `Command` here used to be separated into `command.py`.)
Also, wherever you use `Serial_TCPServer.write()`, you likely were previously encoding every string you passed, either with `str.encode()` or by submitting a bytes string, i.e. `b'MSG\r'`. You no longer need to do …

Separate shared code from several PRs

---

agents/acu/acu_agent.py

Previously, the None values from the ACU status stream were converted to zeros to ensure the data type never changed for the aggregator, and because Influx would not accept float('nan') values.
This update changes handling so the None values are recorded as float('nan') in g3 files. The commanded position values are then sent to their own feeds, which only publish to Influx, and are only published with values are not 'nan'.
Recording the values in g3 files as nan gives no false impressions that the commanded position is actually 0. Splitting the influx publishing into 3 separate feeds for these values allows them to only be published when they have non-nan values.
This update has been tested using the ACU in emulator mode at UCologne.

Acu commanded position None handling

---

agents/acu/acu_agent.py
agents/acu/scan_helpers.py

Update the linear scan generator to improve functionality and testing ability.
- Several values that were hard-coded in the previous version of this function are now optional arguments.
- Problems that previously printed a line and then returned now raise errors.
- The generator now handles values for scan endpoints where the time step size does not divide evenly into the difference between the endpoints. This fix prevents stall-outs and ensures that the correct flags are passed.
Generator was tested in a Jupyter notebook environment. Once the correct values were consistently given by the function, the Agent was updated and the generator process tested with the ACU in emulator mode.

Scan helpers generator

---

.github/workflows/deploy.yml
.github/workflows/develop.yml

This is a more secure way to login to a registry.
Logging in directly results in:
```
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```
Tested logging in on a workflow on push.

Replace docker login with docker/login-action

---

agents/hwp_rotation/rotation_agent.py
docs/conf.py

Mock additional modules. Testing the docs builds on a clean environment the rotation agent was causing build problems if not using `READTHEDOCS=True`.
Avoid the need to use `READTHEDOCS=True` when building locally.
Tested docs builds in a clean virtual environment.

Add mock for rotation agent to docs/conf.py

---

tests/README.rst

See title.
Not providing the library to report coverage on, the current example will run more than the indicated file, and report coverage only for the indicated file, which is not what we want.
Ran locally.

Fix single test file run example

---

.flake8
agents/acu/acu_agent.py
agents/acu/scan_helpers.py

I had set flake8/autopep8 to ignore the `acu_agent.py` and `scan_helpers.py` files from the ACU agent while the `postfat_updates` branch was being worked on in #294. This un-ignores them and runs pre-commit on the files.
There were two flake8 warnings that required more than just a formatting change:
```
agents/acu/acu_agent.py:727:12: F821 undefined name 'end_stop'
agents/acu/acu_agent.py:778:9: F841 local variable 'simulator' is assigned to but never used
```
1. The undefined 'end_stop' wasn't really causing any issues, as it would always evaluate to `False` when undefined.
2. The unused 'simulator' may have affected the use of `fromfile_scan` with the simulator (if the simulator supports such usage.) Rather than remove the unused variable I passed it to `_run_specified_scan()`.
We need …

Run pre-commit hooks on ACU files

---

Dockerfile
setup.py

Title says it all.
We're jumping from a working version of v0.9.0. Highlights for added features include:
- Improvements in `ocs.testing`.
- Minimum required Python version now 3.7 (which is also propagating here.)
- Boolean support in OCS feeds.
Mostly this is for the boolean support, and so we can issue a new socs release.
Not yet tested, will see how unit/integration tests go on this PR.

Bump ocs to v0.9.3 and increase required Python version

---

agents/pfeiffer_tpg366/pfeiffer_tpg366_agent.py
tests/default.yaml
tests/integration/test_pfeiffer_tpg366_agent_integration.py

Implemented integration test for Pfeiffer TPG366 agent, with a typo fix in the agent itself.
The test ensures that `acq` (which runs at startup) is able to collect data and then stop cleanly after
a few seconds. This is the only Operation in the agent at this moment.
Because this agent was lacking an integration test, it was important to add one.
The test runs successfully and does what it intends (runs `acq` for a few seconds, requests it to stop, and then checks that this all happened successfully). The logs indicate successful execution.

Implement Pfeiffer TPG366 integration test

---

agents/lakeshore425/LS425_agent.py

Improved TimeoutLock of the Lakeshore 425 agent.
To run a diagnostic tasks safely without stopping the acquisition process.
Tested by the CHWP setup at UTokyo.

Improved TimeoutLock of Lakeshore425

---

docs/agents/suprsync.rst

Small docs update, `--timeout-wait` was removed in 576e05d5b35095d743418932535df0b1db3869d3.

suprsync: Remove old arg from example config

---

agents/acu/acu_agent.py

This PR contains some changes I made to the Agent while testing updates to the ACU Simulator in the context of the end to end testing and sorunlib development. 
- ada8efa5b7b3bfc21a94505aa68e01ad38c28c13 - Enables the stop command for the `generate_scan()` process. We've discussed running essentially what `stop_and_clear()` does when calling `generate_scan.stop()`, however that won't be possible until work in https://github.com/simonsobs/ocs/pull/253 is complete. For now `generate_scan.stop()` can be called, and one can wait for the scan to complete (as there are still points in the queue), or a `stop_and_clear()` can be called afterwards to clear the queue and immediately stop motion.
- d5b4a38242493980206b6bc35ad2794fc79d0e13 - Removes some sleeps that I don't think need to be there. …

Simulator related ACU Agent Updates

---

agents/synacc/synacc.py
requirements/testing.txt
tests/default.yaml
tests/integration/test_synacc_integration.py

Add integration test for all Operations of synacc agent using mock HTTP server [HttpServerMock](https://github.com/ezequielramos/http-server-mock).
This agent previously lacked an integration test. We are also motivated to have some sort of way to test agents that use HTTP communication, which has ostensibly been accomplished using the mock server.
All test cases pass and the logs look sound.

Add Synacc integration test using mock HTTP test server

---

agents/smurf_file_emulator/smurf_file_emulator.py
tests/agents/test_smurf_file_emulator.py

Try to fix problems that might cause issues with G3tSmurf Indexing
Namely, correct take_g3_data action name, and adds 1-sec sleeps to operations to ensure action timestamps are unique.
To avoid G3tSmurf indexing problems
Hasn't been tested yet

Smurf file em updates

---

agents/sorenson_dlm/dlm_agent.py
tests/default.yaml
tests/integration/test_dlm_agent_integration.py

Implements integration test for DLM agent, with accompanying code comments and fixes that seem appropriate for @tanaybhandarkar to consider/review.
This serves as a necessary integration test for the agent and fixes a few things in the code.
With this test file and agent code, the tests all pass and the code seems to work under my (@erfz) expectations. Of course, @tanaybhandarkar should only take these changes as suggestions.

DLM agent integration test and code comments/fixes

---

agents/labjack/Dockerfile

This PR updates the Docker build to fetch the LJM library from a new location on their website. It also now use PyPI for downloading labjack-ljm instead of from their website. Note this now has a newer version of that library than we were using (1.21.0 vs 1.20.0).
Labjack moved their downloads to a CDN. 
Not yet tested.

Update labjack software installation in Docker build

---

agents/pysmurf_controller/Dockerfile

Bump sodetlib

---

.github/workflows/deploy.yml
.github/workflows/develop.yml
.github/workflows/pytest.yml

This fixes an issue with installing the required dependencies when building and testing the wheel that gets published to PyPI.
After a recent merge into the `develop` branch this workflow failed.
https://github.com/simonsobs/socs/actions/runs/3348424031/jobs/5547584119
Testing in this PR by adding the job to the pytest workflow temporarily.

Fix develop/deploy wheel tests

---

agents/pfeiffer_tpg366/pfeiffer_tpg366_agent.py
tests/default.yaml
tests/integration/test_pfeiffer_tpg366_agent_integration.py

Added test mode so integration test can run without using `time.sleep`
`Time.sleep` can sometimes cause failing, instead use `acq.wait()` with a test mode
Passes pytest

Pfeiffer_tpg366 agent added test mode for integration test

---

.github/workflows/deploy.yml
CONTRIBUTING.rst
README.rst
docs/agents/acu_agent.rst
docs/agents/holo_fpga.rst
docs/agents/holo_synth.rst
docs/agents/latrt_xy_stage.rst
docs/agents/pysmurf-controller.rst
docs/user/installation.rst
setup.py

This PR removes the direct references from `setup.py`. It also enabled deployment to PyPI when pushing certain pre-release tags. This will allow testing of releases before making an official release.
The Agents that no longer have an installation variant now have their dependencies documented, with easily to copy pip install lines pointing to the previously used direct references. 
On release v0.4.0 (#369) the publication to [PyPI broke](https://github.com/simonsobs/socs/discussions/369#discussioncomment-4101714). This was due to using direct references in `setup.py`. Removing these should allow future releases to successfully publish.
Will be tested with pre-release tag publication. That pre-release tag system is already setup on ocs. Also, the v0.4.0 version of socs that's [on PyPI …

Remove direct references from setup.py

---

docker/pysmurf_controller/Dockerfile

Title says it all.
Includes new ocs v0.10.1.
Imports and related tools checked for locally. Need to test on actual system.

Bump sodetlib image base version

---

README.rst

Fixes the GitHub Actions workflow badge.
URL was changed upstream. See https://github.com/badges/shields/issues/8671.
Looked at the README on this branch.

Fix github actions workflow badge

---

docker/pysmurf_controller/Dockerfile

Bumps the sodetlib docker version to fix a dateutil import error.

Bump sodetlib docker version

---

socs/snmp.py

This fixes the MIB search for SNMP agents.
(Thanks to @davidvng for helping debug this.)
Resolves #401.
A locally updated image has been run with the UPS agent at the site and is now working.

Fix MIB location search for SNMP agents

---

Dockerfile

Update to latest base image from ocs, in prep for new socs release.
Preparing for socs v0.4.1 release.
Built image locally. v0.10.1 was mostly bug fixes from ocs.

Bump base ocs docker image version

---

README.rst

See title.
I missed some links to 'master' in #410.
Untested.

Remove stray links to 'master' branch

---

socs/db/suprsync.py

This is a very tiny fix, in a code path that's rarely activated.

suprsync: fix unformatted log message

---

socs/testing/device_emulator.py

This PR catches the error that occurs when the device emulator can't bind to a port. This happens if another device emulator instance isn't properly shutdown yet. This occasionally happens when running the tests (though I can't seem to reproduce that behavior locally, just on GH Actions.)
The emulator now simply waits a second and tries again until it can bind to the port. If it hangs, something else is going on and the user will have to abort the tests.
This is a better solution to the problem initially solved by #412. While #412 did help on the next run, a future run again produced an error related to the address already being in use. This wasn't solved by #412 because the device emulators within a single test file tend to bind to the same port, and it was device emulators used within a …

Catch error in device emulator when binding to port

---

socs/agents/smurf_file_emulator/agent.py

While looking at end-to-end testing data, found a couple of bugs which was causing large numbers of dropped samples, and ~20us variation between timestamps of different slots. This PR should fix both those issues.
- The "write_next" function will take the previous stop time as the next starting time.
- Use `np.linspace` instead of `np.arange` to fix floating point buildup
better end-to-end test data.
Tested on simons1 to check this fixes both issues.

Fixes sampling issues with file emulator

---

.github/workflows/develop.yml
.github/workflows/pytest.yml
.github/workflows/skipped-pytest.yml
.github/workflows/skipped-test-build.yml
.github/workflows/test-build.yml
.readthedocs.yaml
docs/agents/cryomech_cpa.rst

See title.
Docs for the Cryomech agent were out of date, stating that control wasn't yet implemented.
Not tested, docs only change.

Update state of control functionality in cryomech agent description

---

requirements.txt
setup.py
tests/integration/test_ibootbar_agent_integration.py

Using pysnmp-lextudio instead of pysnmp since it is actively being maintained. Using pyasn1==0.4.8 for now until compatibility with pysnmp is fixed.
Fixes #434

Use pysnmp-lextudio and pyasn1==0.4.8

---

socs/agents/ups/agent.py

Attempt at fixing UPS agent connection issue.
Resolves #415. 
Has not been tested on a UPS, but has been tested on an ibootbar. Assuming SNMP works the same way for both.

Fix UPS Agent connection issue 

---

socs/agents/labjack/agent.py

This PR adds some code to find the calibration curve location within the labjack agent directory.
Resolves #450.
Tested at Penn.

Find calibration curve location within package

---

socs/agents/smurf_file_emulator/agent.py
tests/agents/test_smurf_file_emulator.py

Adds `tag` param to smurf-file-emulator operations to match those in the pysmurf-controller.
Required for e2e testing of real schedules
tests ran locally

Adds user tag param to the smurf file emulator ops

---

socs/agents/acu/agent.py

Small docs fix I noticed when working with the Agent API over in sorunlib.

Update set_boresight method signature override

---

socs/db/suprsync.py

Adds a filter on TimecodeDir.archive_name when updating tcdirs
Resolves #507 
See issue #507 
not yet, but simple change.

Adds archive_name filter to update timecode func

---

docker/wiregrid_actuator/Dockerfile

See title.
The CMD was overriding the crossbar address configuration set by environment variables when trying to setup at the site.
I built a test image at the site and ran it with this patch. It's working.

Remove CMD from wg-actuator dockerfile

---

socs/agents/wiregrid_actuator/agent.py
socs/agents/wiregrid_kikusui/agent.py

I'm not entirely sure how this is happening, but autopep8 missed this automatic formatting in #512, but is catching it in #429. Just PRing it to separate it from #429.

Cherry-pick of missed pre-commit run

---

docker/pysmurf_controller/Dockerfile

Bump sodetlib to the version with working jupyter-lab

Bump sodetlib docker

---

socs/agents/pysmurf_controller/agent.py

See title. Only docstrings changed here.
Noticed some missing args in the method signature override when referencing the API.
Built docs locally.

Add missing in pysmurf-controller docstrings

---

socs/agents/labjack/agent.py

See title.
I needed this structure documented for writing code in sorunlib, so I grabbed and reduced this example from a running labjack agent at site.
Docs change only, based on in field agent.

Add example session.data structure for labjack acq process

---

socs/agents/pysmurf_controller/agent.py

Bugfix caught while testing the zero_biases task

Bugfix in zero-biases fn

---

.github/dependabot.yml
.github/workflows/develop.yml
.github/workflows/pytest.yml
.github/workflows/skipped-pytest.yml
.github/workflows/skipped-test-build.yml
.github/workflows/test-build.yml

This'll enable automatic updates of the ocs base image in the Dockerfile for socs. I also added myself as reviewer to these dependabot PRs.
ocs v0.10.3 released the other day, just automating the update process.
Hasn't been tested yet, but I use this on other repos already too.

Add docker updates to dependabot and set reviewers

---

socs/agents/acu/agent.py

"Speed mode" provides the only known means to set, from the remote interface, how quickly the ACU seeks to new positions in Preset mode.  This control was requested by SATP3 team.
Tested on SATP2, with correspondingly updated ocs-web.

ACU: add set_speed_mode task

---

socs/agents/ucsc_radiometer/agent.py

updated requests timeout to 60 seconds for radiometer agent
Has been tested on radiometer agent in `dev` environment

change HTTP requests timeout to 60s

---

docs/agents/acti_camera.rst
socs/agents/acti_camera/agent.py

Adds resolution as a parameter to the ACTi Camera agent.
Some specific camera models cannot interpret the previous hardcoded resolution.
Will be tested on site cameras.

ACTi Camera Agent add resolutions as parameter

---

docs/agents/synacc.rst
socs/agents/synacc/agent.py
tests/integration/test_synacc_integration.py

Adds outlet names as a parameter to SynAccess agent.
Resolves #625 
To be tested with ocs-web on site.

SynAccess agent add outlet names

---

simulators/lakeshore240/ls240_simulator.py
socs/agents/acu/agent.py
socs/agents/hwp_gripper/agent.py
socs/agents/lakeshore372/agent.py

Trying to test pre-commit running on current `main`.
pre-commit is [making modifications](https://github.com/simonsobs/socs/pull/558/commits/8e0219325429ad68aceee977ced8a0b96e8d151a) to files in #558. I'm not sure why, as running on all files on the current `main` branch doesn't produce the changes it's making on the `syncbox` branch. I'm very confused.
The changes are fine, so if this doesn't trigger them again, I'm going to cherry-pick them from #558 to keep things strictly relevant to that PR.
Very meta, this PR is the test.

Re-run pre-commit on all files

---

docs/agents/meinberg_syncbox_agent.rst
docs/index.rst

See title.
Noticed this was left off when I was looking for the docs during a review.
Built locally.

Add Meinberg Syncbox Agent docs to index

---

README.rst

Updates the test runner badge to track the runs on `main`.
The develop workflow is run on merges to `main`, which is really what we want to track in this badge, rather than arbitrary runs from PRs that might be failing, which is what we're getting now.
Viewed the badge in this branch.

Fix tests runner badge in README

---

socs/agents/pysmurf_controller/agent.py
socs/agents/pysmurf_controller/smurf_subprocess_util.py

Added Psat to published quantiles from take_iv task in pysmurf_controller agent. Addresses request by @kmharrington in issue #698 
Improved, fast turn around data-quality metrics.
Resolves #698 
I didn't test anything yet.

Added Psat to published quantiles from take_iv task in pysmurf_controller agent

---

docs/requirements.txt

This just pins the sphinx-argparse package to a working version. Note that we should unpin this when the bug gets resolved.
Release v0.5.0 introduced a bug with the use of autodoc_mock_imports [1].
[1] - https://github.com/sphinx-doc/sphinx-argparse/issues/56
Readthedocs build will happen on this PR.

Pin sphinx-argparse package

---

Dockerfile

Title says all.
I'd like to make a release of socs that has the changes from v0.11.1 before moving forward with the Dockerfile rework from https://github.com/simonsobs/ocs/pull/397.
Builds and tests run locally, will also see that in the CI.

Bump ocs base image to v0.11.1

---

requirements.txt
setup.py

Pin `pysnmp==4.4.12`
PyPi of `pysnmp` recently became the same as `pysnmp-lextudio` which removed twisted.

Pin pysnmp version to 4.4.12

---

docs/agents/hwp_pcu.rst

See title.
Found this while reviewing a config change at site.
Docs only change, not tested.

Remove unused --mode arg from example config

---

socs/agents/suprsync/agent.py
socs/db/suprsync.py

Adds configuration options to suprsync agents to echo DB commands, and increase pool and overflow limits.
This is to try to fix https://github.com/simonsobs/socs/issues/734. 
This is currently running on SATP2. I don't know yet whether it will actually help with the crashes, but I think its not a bad idea for these options to be merged anyway.

Adds extra db connection options to suprsync agent

---

socs/agents/bluefors/agent.py
socs/agents/scpi_psu/agent.py

This change makes the file search in the bluefors agent case insensitive.
This was split out from #763.
Some labs might name their files "heaters" vs "Heaters". See #763.
Tested on the OCS system in Texas by @CAWNoodle.

Make bluefors file search case insensitive

---

socs/agents/rtsp_camera/agent.py

Catches reconnection failing to continue attempts instead of trying to grab screenshots
Resolves #828

RTSPCameraAgent: Catch reconnection attempt fail

---

docker-compose.yml
docker/wiregrid_actuator/Dockerfile
docs/agents/wiregrid_actuator.rst

Modify `docker/wiregrid_actuator/Dockerfile` in installing gclib python library.
fix bug in building image of wiregrid_actuator

fix bug in building image of wiregrid_actuator

---

socs/plugin.py

This is a bug fix in `plugin.py`
`plugin.py` has wrong path to the PCR500MA module, preventing docker container boot up correctly.
Confirmed that `ocs-agent-cli --instance-id stimulator-pcr500ma` works correctly.

fix: wrong module name

---

socs/agents/hwp_supervisor/agent.py

Just a quick docstring fix.
I noticed the missing arguments while reviewing https://github.com/simonsobs/sorunlib/pull/202.
Not tested, docstring only change.

Add default pmx_off arguments to docstring

---

docker/wiregrid_actuator/Dockerfile

This just fixes the URL for installing gclib from the vendor.
[Recent builds](https://github.com/simonsobs/socs/actions/runs/13705712760/job/38330362120?pr=826) have been failing. Upstream seems to have started building wheels instead of serving a tarball. See updated instructions in [1].
[1] - https://www.galil.com/sw/pub/all/doc/gclib/html/
Tested builds and installation locally. The latest image published produces:
```
$ docker run -it --rm --entrypoint=/bin/bash simonsobs/ocs-wgactuator-agent:v0.5.2-40-g6770a7d-dev
root@d1f9c4742571:/home/ocs# python
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gclib; print(f'gclib location: {gclib.__file__}'); print(f'gclib version: …
```

Update gclib URL to point to new wheel

---

socs/agents/hwp_pmx/drivers/PMX_ethernet.py

fix error message of hwp-pmx
No test

fix error message of hwp-pmx

---

socs/agents/pysmurf_controller/agent.py

Publishes some `check_state` results to feed
Resolves #854

PysmurfController: publish check_state results to feed

---

docker/pysmurf_controller/Dockerfile

Include the latest tag of `sodetlib` in the `pysmurf-controller` docker.
We'd like to deploy the latest features in `sodetlb`, in particular support for fixed tones.
Individual features were tested before being merged in `sodetlib`

update sodetlib version in pysmurf-controller docker.

---

socs/agents/pysmurf_monitor/agent.py

This adds a debug log when the pysmurf-monitor writes to the database.
This will be helpful to see typical duration in practice and will be informative for possibly increasing the default timeout in the suprsync agent, which reads from this database.
Tested locally via the existing integration tests with:
```
LOGLEVEL=debug python -m pytest integration/test_pysmurf_monitor_integration.py
```

pysmurf-monitor: Log db write time as debug

---

socs/agents/acu/agent.py

set_shutter(target) will quickly succeed, rather than fail, if shutter is already state target.
This is a more convenient functionality in practice; otherwise caller has to check state before requesting desired state.
Tested on LAT today.

ACU: set_shutter will not fail if already in req state

---

socs/agents/pysmurf_controller/agent.py

This PR is to add new feed for relock.
Based on the feeds (number of good/all detectors) we have, just add new feed being calculated as 1 if bad(all - good) > good, else 0.
This is for new alarm that check relock quality.
In terms of making new alarm of this, calculating this with the feeds (number of good/all detectors) we have after publishing is computational intense. Thus, I would like to make those values here and publish them in addition to the current feeds
Not yet on the site computer but I hope we do not need to test because this is simple change.
Script itself has been tested as below, which is expected.
```
alls = np.array([100,100,100,100,100,100])
goods = np.array([30,40,49,50,51,80])
block_data = {}
for iband, (iall, igood) in enumerate(zip(alls, goods)): …
```

add new feed for relock alarm
